// Comentarios de estudio — días 1 a 31
// Línea teológica: bautista reformada, confesional (1689), pactual.
// Campos: t=título, h=contexto histórico, c=contexto cultural,
// n=análisis narrativo, p=teología bíblica y pactual, v=voces (autores), q=pregunta de meditación.
const COMENTARIOS = {
 1: {
  t: "La creación, el pacto de obras y la caída",
  h: "Génesis fue escrito por Moisés para Israel en el desierto, un pueblo recién redimido de Egipto que necesitaba saber quién era su Dios frente a las cosmogonías paganas. Génesis 1–3 no es un mito más del antiguo Cercano Oriente: es una polémica deliberada. Donde Babilonia contaba que el mundo nació de la violencia entre dioses (Enuma Elish), Moisés declara que un solo Dios, sin rival ni esfuerzo, creó todo por su palabra. El sol y la luna —deidades para Egipto y Mesopotamia— ni siquiera reciben nombre: son 'lumbrera mayor' y 'lumbrera menor', meras criaturas al servicio del hombre.",
  c: "En las culturas del antiguo Cercano Oriente, solo los reyes eran 'imagen' de los dioses; las imágenes de culto representaban a la deidad en su templo. Génesis democratiza y dignifica: todo ser humano, varón y hembra, es imagen de Dios (1:26-27). El Edén está descrito con lenguaje de santuario —oro, bedelio, ónice, querubines guardando la entrada— que Israel reconocería después en el tabernáculo. Adán es puesto para 'labrar y guardar' (2:15), los mismos verbos del servicio levítico (Nm 3:7-8): el primer hombre fue un sacerdote-rey en el templo-jardín.",
  n: "La estructura es magistral: seis días formando y llenando (días 1-3 forman los reinos; días 4-6 los llenan de reyes), culminando en el reposo del séptimo día, que no tiene 'tarde y mañana' —una invitación abierta al reposo de Dios (cf. Heb 4). El capítulo 2 no contradice al 1: enfoca la cámara sobre el sexto día. El capítulo 3 invierte todo el orden: la serpiente (criatura) manda, la mujer decide, el hombre calla y sigue. La caída es una inversión de la creación. Pero el juicio viene entrelazado con gracia: antes de maldecir al hombre, Dios promete un Redentor.",
  p: "Aquí están las semillas de toda la teología pactual. Dios entró en pacto con Adán como cabeza federal de la humanidad: vida condicionada a la obediencia perfecta, muerte por la desobediencia (el 'pacto de obras', cf. Os 6:7; Ro 5:12-19). Adán cayó, y en él todos nosotros. Pero Génesis 3:15 —el protoevangelio— es la primera revelación del pacto de gracia: la simiente de la mujer aplastará la cabeza de la serpiente, siendo herida en el proceso. Toda la Escritura desde aquí es el despliegue de esa promesa hasta Cristo, el postrer Adán, que obedeció donde el primero falló.",
  v: "Nehemiah Coxe: 'Desde la caída, Dios nunca trató con el hombre sino a través de un Mediador prometido'. Matthew Henry observa que Dios predicó el primer evangelio en el mismo lugar del primer pecado. Thomas Boston llamó a Gn 3:15 'el evangelio en germen'. Ver también John Gill (Exposición, Gn 3) y la Confesión de 1689, caps. 4, 6 y 7.",
  q: "Si Adán fue tu representante y caíste en él, ¿descansas hoy en la obediencia del postrer Adán como tu única justicia?"
 },
 2: {
  t: "Caín, el diluvio y las dos simientes",
  h: "Génesis 4–7 cubre desde el primer homicidio hasta el diluvio. Las genealogías de Caín y de Set no son relleno: trazan las dos líneas anunciadas en 3:15, la simiente de la serpiente y la simiente de la mujer. Culturas mesopotámicas conservaron memorias de un gran diluvio (Gilgamesh, Atrahasis), lo cual confirma que el evento quedó grabado en la memoria de los pueblos; pero solo Génesis lo explica moralmente: no dioses caprichosos molestos por el ruido humano, sino un Dios santo que juzga la violencia y corrupción de la tierra (6:11-13), y que salva por gracia mediante un pacto.",
  c: "La cultura cainita es la primera civilización: ciudades, ganadería, música, metalurgia (4:17-22). El texto no condena la cultura en sí, pero muestra su ambigüedad: el progreso técnico convive con la venganza desmedida de Lamec, cuya canción de espada (4:23-24) es el primer poema humano registrado —y celebra el homicidio. Frente a ello, la línea de Set se define por algo aparentemente pequeño: 'entonces los hombres comenzaron a invocar el nombre de Jehová' (4:26). El culto público es la marca de la simiente santa.",
  n: "Nota el paralelo entre Caín y sus padres: Dios interroga ('¿dónde está Abel tu hermano?' como '¿dónde estás tú?'), el pecador evade, cae la maldición, y aun así hay una marca de protección inmerecida. El pecado 'está a la puerta, agazapado' como fiera (4:7): la primera descripción psicológica del pecado en la Biblia. La genealogía de Génesis 5 martilla ocho veces 'y murió' —la paga del pacto de obras roto— pero Enoc rompe el ritmo: 'caminó con Dios, y desapareció'. La muerte no tiene la última palabra para los que caminan con Dios.",
  p: "Noé 'halló gracia' (6:8) antes de ser llamado justo (6:9): el orden es crucial, gracia primero, justicia después. Dios anuncia aquí su primer pacto explícito con la palabra berit (6:18). El diluvio es a la vez juicio y salvación: las mismas aguas que ahogaron al mundo levantaron el arca. Pedro tomará esta figura para el bautismo (1P 3:20-21): juicio sobre el viejo mundo, salvación para los que están 'en' el refugio provisto por Dios. El arca es Cristo: una sola puerta, cerrada por Dios mismo (7:16).",
  v: "Matthew Henry: 'Dios cerró la puerta, para mostrar que la salvación de principio a fin es del Señor'. John Bunyan vio en el arca la figura de la seguridad del creyente. Ver John Gill sobre Gn 6:18, primera mención formal de pacto.",
  q: "La generación de Noé comía, bebía y edificaba hasta que llegó el diluvio (Mt 24:38). ¿Vives tú velando, o adormecido por la normalidad?"
 },
 3: {
  t: "El pacto con Noé y la torre de Babel",
  h: "Tras el diluvio, la historia se reinicia con ecos deliberados de la creación: viento sobre las aguas, tierra que emerge, mandato de fructificar. Génesis 10, la 'tabla de las naciones', es un documento único en la literatura antigua: ningún otro pueblo escribió una genealogía universal de la humanidad, porque ningún otro pueblo creyó en un solo Dios de todas las naciones. Babel (11) explica históricamente la dispersión de lenguas y pueblos, y teológicamente prepara el llamado de Abraham: cuando las naciones se pierden, Dios escoge a un hombre para bendecirlas a todas.",
  c: "Los zigurats mesopotámicos eran torres-templo con escaleras hacia el cielo; su nombre en Babilonia significaba 'puerta del dios'. Los constructores de Babel usan ladrillo y asfalto —tecnología mesopotámica— para 'hacerse un nombre' y evitar ser dispersados, en rebeldía directa al mandato de llenar la tierra. La ironía del texto es demoledora: la torre que pretendía llegar al cielo es tan pequeña que Dios tiene que 'descender' para verla (11:5).",
  n: "El pacto noético (8:20–9:17) responde al problema planteado por el diluvio: si Dios juzga el pecado con justicia, y el corazón humano sigue siendo malo 'desde su juventud' (8:21), ¿cómo puede continuar la historia? Respuesta: Dios se compromete unilateralmente a sostener el orden natural hasta el fin, colgando su arco de guerra en las nubes, apuntando hacia arriba. La escena de Noé ebrio y Cam muestra que el diluvio no lavó el pecado del corazón: el 'nuevo mundo' necesita algo más que aguas; necesita la simiente prometida.",
  p: "El pacto con Noé es un pacto de preservación común: incluye a toda carne, garantiza el escenario estable sobre el cual se desplegará el pacto de gracia. No salva, pero sostiene el mundo para que la salvación llegue. Babel y Pentecostés se responden mutuamente: allí Dios confundió las lenguas para dispersar la soberbia; en Hechos 2 el Espíritu atraviesa todas las lenguas para reunir un pueblo. La ciudad que el hombre no pudo edificar hacia arriba, Dios la hace descender: la nueva Jerusalén (Ap 21).",
  v: "Nehemiah Coxe dedicó un capítulo entero al pacto noético como fundamento de la providencia común. Calvino sobre el arcoíris: 'un espejo de la paternal benevolencia de Dios'. Matthew Henry: 'los hombres edifican para su nombre; Dios edifica para el suyo'.",
  q: "¿Qué 'torres' construyes para hacerte un nombre, en lugar de invocar el Nombre que ya te fue dado?"
 },
 4: {
  t: "Job: el justo probado — el telón se levanta",
  h: "Leemos Job aquí porque casi todos los indicios lo sitúan en la era patriarcal: riqueza medida en ganado, Job como sacerdote de su familia, longevidad de 140+ años, ausencia total de referencia a la ley, el sacerdocio o el éxodo, y el nombre divino 'Shaddai' (Todopoderoso), típico de los patriarcas. La tierra de Uz se ubicaba probablemente al este de Canaán, hacia Edom o Arabia del norte. Job es quizás el libro más antiguo de la Biblia: antes de que existiera Israel, ya existía la pregunta del sufrimiento del justo, y Dios ya tenía respuesta.",
  c: "El diálogo sapiencial sobre el sufrimiento existía en Mesopotamia ('Ludlul bel nemeqi', el 'Job babilónico'), pero la diferencia es abismal: el sufriente pagano nunca sabe qué dios ofendió ni por qué; Job trata con un Dios personal, conocido, con quien puede litigar. Los capítulos 1–2 usan la escena de la corte celestial, familiar en el mundo antiguo, pero con un giro: 'el satán' (el acusador) no es un dios rival sino un funcionario subordinado que necesita permiso para cada movimiento. El mal está bajo correa.",
  n: "El lector recibe lo que Job nunca recibe: la vista del telón celestial. Este es el genio narrativo del libro: sabemos por qué sufre Job, y sabemos que él no lo sabe, y que nunca se le dirá. La apuesta del acusador es la pregunta más profunda del libro: '¿acaso teme Job a Dios de balde?' (1:9) — ¿es posible amar a Dios por Dios mismo y no por sus regalos? Las respuestas de Job en 1:21 y 2:10 son las cumbres: adoración en la ruina. Luego llegan los amigos, se sientan en silencio siete días —lo mejor que hicieron— y el capítulo 3 estalla: Job maldice su día, no a su Dios.",
  p: "Job plantea el problema que solo el evangelio resolverá: ¿puede haber un justo que sufra, no por sus pecados, sino para la gloria de Dios? La teología de la retribución estricta (sufres porque pecaste) que defenderán los amigos es exactamente la teología que la cruz demuele: el único perfectamente Justo sufrió lo que ningún hombre sufrió. Job, despojado de todo y adorando entre cenizas, es sombra del Varón de dolores. Santiago 5:11 nos da la clave de lectura: 'habéis oído de la paciencia de Job, y habéis visto el fin del Señor: que el Señor es muy misericordioso y compasivo'.",
  v: "Joseph Caryl, puritano, predicó Job durante 24 años (12 volúmenes): 'Dios afligió a Job no porque no lo amara, sino porque lo amaba'. Thomas Watson: 'Dios tiene un propósito de amor en cada golpe'. Calvino predicó 159 sermones sobre Job.",
  q: "Si Dios te quitara todo lo que te ha dado, ¿quedaría algo entre tú y Él? ¿Le temes de balde?"
 },
 5: {
  t: "El consuelo que hiere: primer ciclo de discursos",
  h: "Los capítulos 6–9 nos meten de lleno en el primer ciclo de diálogos. Elifaz —probablemente de Temán, en Edom, región célebre por sus sabios (Jer 49:7)— ya abrió el debate apelando a una visión nocturna y al principio de retribución: el que siembra iniquidad, eso siega. Bildad apelará a la tradición de los antiguos. La sabiduría del antiguo Cercano Oriente funcionaba así: experiencia, tradición y observación del orden del mundo. Todo correcto en general — y cruelmente falso aplicado a Job.",
  c: "El discurso de Job en el cap. 7 usa imágenes laborales de su tiempo: el jornalero que espera su paga, el esclavo que anhela la sombra, el tejedor cuya lanzadera corre. La vida como 'milicia' (7:1) refleja el servicio forzado bajo los imperios. En 9:33 Job clama por un 'árbitro' (mokhiakh), figura jurídica del mundo antiguo: alguien con autoridad para poner la mano sobre ambas partes en un litigio. Ningún tribunal humano podía sentar a Dios en el banquillo; Job intuye que necesita un mediador que sea igual a Dios e igual a él.",
  n: "Observa la asimetría trágica: los amigos hablan sobre Dios; Job habla cada vez más a Dios. Aun sus quejas más ásperas (7:11-21) son oración. Esa es la diferencia entre la fe que lucha y la incredulidad que abandona. El capítulo 9 es teológicamente asombroso: Job confiesa la trascendencia de Dios mejor que sus amigos ('¿cómo se justificará el hombre con Dios?', 9:2) y precisamente por eso desespera: ¿de qué sirve tener razón si tu contraparte es omnipotente? Su pregunta correcta espera respuesta en otro monte y otro madero.",
  p: "Job 9:33 es uno de los gemidos mesiánicos más puros del Antiguo Testamento: 'No hay entre nosotros árbitro que ponga su mano sobre nosotros dos'. Lo que Job pide es exactamente lo que 1 Timoteo 2:5 anuncia: 'hay un solo Dios, y un solo mediador entre Dios y los hombres, Jesucristo hombre'. La teología pactual lee aquí el anhelo universal que el pacto de gracia satisface: un Mediador que puede tocar al Santo sin ser consumido y al miserable sin despreciarlo.",
  v: "Joseph Caryl sobre 9:33: 'Job deseaba a Cristo sin saber su nombre'. John Owen: toda la comunión con Dios es comunión mediada. Matthew Henry: 'los que se apresuran a condenar suelen ser los más lentos en consolar'.",
  q: "Cuando consuelas a un afligido, ¿hablas como Elifaz —teología correcta, aplicación cruel— o pones tu mano en su hombro antes que tu doctrina en su herida?"
 },
 6: {
  t: "«Aunque él me matare»: la fe que litiga",
  h: "Continúa el primer ciclo: Zofar, el más duro de los tres, acusa a Job sin rodeos (11): 'Dios te castiga menos de lo que mereces'. La respuesta de Job (12–14) cierra el ciclo con un tour de force: ironiza ('vosotros sois el pueblo, y con vosotros morirá la sabiduría', 12:2), confiesa la soberanía absoluta de Dios sobre naciones y jueces (12:13-25), y anuncia que llevará su caso directamente ante el Todopoderoso (13:3). En el mundo antiguo, litigar contra un rey era jugarse la vida; Job lo sabe: 'he aquí, aunque él me matare, en él esperaré' (13:15).",
  c: "El capítulo 14 medita sobre la muerte con la imagen más conmovedora del libro: el árbol cortado que retoña 'al percibir el agua' frente al hombre que muere y no se levanta. En Canaán y Egipto abundaban mitologías de dioses que morían y renacían con las estaciones; Job no apela a mitos sino que hace una pregunta desnuda y honesta: 'si el hombre muriere, ¿volverá a vivir?' (14:14). Y deja caer un destello: 'llamarás, y yo te responderé; tendrás afecto a la hechura de tus manos' (14:15).",
  n: "El movimiento interno de Job es fascinante: en el mismo discurso pasa de la desesperación al atisbo de esperanza y de vuelta. No es incoherencia: es la fe real bajo presión, que oscila pero no suelta. Nota el giro jurídico: Job ya no quiere solo alivio, quiere audiencia. 'Quita de sobre mí tu mano... llama, y yo responderé' (13:21-22). El sufrimiento ha empujado a Job de la pregunta '¿por qué me pasa esto?' a la pregunta mejor: '¿dónde está Él?'. Los amigos discuten un principio; Job busca una Persona.",
  p: "'Aunque él me matare, en él esperaré' es la definición misma de la fe del pacto: confianza en Dios contra toda evidencia visible, fundada en su carácter y no en las circunstancias. Es la fe de Abraham en Moriah, de Habacuc ante la higuera sin fruto, del Hijo en Getsemaní. Y la pregunta de 14:14 recibirá respuesta definitiva no con un argumento sino con una tumba vacía: 'porque yo vivo, vosotros también viviréis' (Jn 14:19).",
  v: "Thomas Manton: 'la fe es más fuerte cuando espera contra la esperanza'. Spurgeon predicó de 13:15: 'fe colosal, que confía en Dios con la espada de Dios sobre el cuello'. Joseph Caryl: 'la fe puede leer amor en el rostro airado de Dios'.",
  q: "¿Tu fe depende de que Dios te trate bien según tu criterio, o de quién es Él aunque no entiendas su mano?"
 },
 7: {
  t: "«Yo sé que mi Redentor vive»",
  h: "Días 14–16 del libro: segundo ciclo de discursos. Los amigos endurecen su posición —ya no insinúan, acusan— y Elifaz pinta al malvado atormentado (15), retrato dirigido a Job. La respuesta de Job en 16–17 acuña la expresión 'consoladores molestos' (16:2). En medio de este ciclo cada vez más oscuro brillará (en la lectura de mañana, 19:25) la cumbre del libro. Hoy, en 16:19, ya apunta el amanecer: 'mi testigo está en los cielos, y mi testimonio en las alturas'.",
  c: "El lenguaje de Job 16 es forense y bélico: Dios lo ha 'desgarrado', lo entregó al 'inicuo', lo puso como 'blanco' de arqueros. Rasgarse el saco y echar polvo sobre la cabeza (16:15) eran los ritos de duelo del antiguo Cercano Oriente; Job dice que ha 'cosido' el cilicio sobre su piel: duelo permanente. La figura del 'testigo celestial' (16:19) evoca los tratados antiguos, donde los testigos garantizaban el cumplimiento; Job apela a un garante en el cielo contra la sentencia que la tierra ya dictó sobre él.",
  n: "La paradoja más audaz del libro se agudiza: Job apela a Dios contra Dios. El Dios que (según su percepción) lo destroza es el mismo ante quien clama por vindicación. La fe de Job se niega a partir a Dios en dos: no huye de Él hacia los ídolos ni hacia el ateísmo, sino que huye de Dios airado hacia Dios justo. Esa intuición —que en Dios mismo hay un Vindicador para el que Dios aflige— es el corazón evangélico del libro, y solo la cruz la explicará del todo.",
  p: "El 'testigo en los cielos' (16:19) y el 'Redentor' (goel, 19:25) pertenecen a la misma constelación: el goel era el pariente cercano con derecho a rescatar la tierra, redimir al esclavo y vengar la sangre (Lv 25; Rut). Job confiesa que su Pariente-Redentor vive, y que 'al fin se levantará sobre el polvo' y que él lo verá con sus propios ojos, resucitado. Cristo es ese Goel: se hizo pariente nuestro en la encarnación para tener derecho de rescate, y pagó el precio en sangre. Job vio de lejos el día de Cristo, y se gozó.",
  v: "John Gill defendió la lectura de 19:25-27 como confesión de resurrección corporal. El 'Mesías' de Händel abre su tercera parte con este texto. Matthew Henry: 'la fe de Job edificó un altar sobre las ruinas de su casa'.",
  q: "Job confesó a su Redentor vivo desde el muladar, sin ver nada. Tú, que conoces el nombre del Goel y su tumba vacía, ¿vives a la altura de lo que sabes?"
 },
 8: {
  t: "El endurecimiento del debate y la miseria del moralismo",
  h: "Capítulos 17–20: agoniza el segundo ciclo. Bildad (18) recita el catálogo del destino del impío —lazos, red, terrores, memoria borrada— y Zofar (20) añade el suyo: el gozo del malvado es breve, vomitará las riquezas que tragó. Como poesía, son piezas magistrales de la tradición sapiencial; como pastoral, son crueldad refinada: todos los dardos apuntan al hombre en cenizas que tienen delante. Job 19, en el centro, responde con la cumbre que ya vimos: el Redentor vivo.",
  c: "Las imágenes de Bildad reflejan supersticiones antiguas sobre la muerte: 'el primogénito de la muerte' (18:13) y 'el rey de los espantos' (18:14) evocan la demonología cananea y mesopotámica (Mot, el dios cananeo de la muerte). Que la lámpara del impío se apague y su memoria perezca de la tierra era, en una cultura sin doctrina clara de resurrección, la peor maldición concebible: la aniquilación del nombre. Por contraste, Job pide que sus palabras se graben 'en piedra con cincel de hierro y plomo para siempre' (19:23-24) — y su deseo se cumplió más de lo que imaginó: están en la Escritura eterna.",
  n: "Nota la mecánica del debate: cuanto menos argumentos tienen los amigos, más gritan. Ya no consuelan ni razonan: recitan. El moralismo siempre termina así, en fórmulas sin rostro. Mientras tanto Job describe su abandono total (19:13-19): hermanos alejados, esposa que no soporta su aliento, niños que lo desprecian. Es el retrato del justo desamparado que los salmos retomarán (Sal 88) y que Cristo encarnará: 'todos los discípulos, dejándole, huyeron'. Precisamente desde ese abandono absoluto brota la confesión más alta del libro. La fe no florece a pesar del desierto; a veces florece por él.",
  p: "La teología de Bildad y Zofar es cierta a medias: sí, hay juicio para el impío; no, no todo sufrimiento es ese juicio. El error no está en su doctrina de la retribución sino en su cronología y su aplicación: exigen que Dios salde todas las cuentas dentro de esta vida, y le niegan el derecho de tener propósitos que ellos no conocen. La cruz es la refutación final: allí el Justo fue tratado como culpable para que culpables fueran tratados como justos. Quien entiende la cruz jamás vuelve a leer el sufrimiento ajeno como aritmética de pecados.",
  v: "Jeremiah Burroughs ('La joya rara del contentamiento cristiano'): 'Dios a menudo aflige más a los que más ama, porque los está preparando para más gloria'. Joseph Caryl: 'juzgar el corazón por la cruz que uno carga es usurpar el tribunal de Dios'.",
  q: "¿Mides la espiritualidad de otros (o la tuya) por su prosperidad o su dolor? ¿Qué revela eso de tu doctrina de la cruz?"
 },
 9: {
  t: "¿Por qué prosperan los impíos?",
  h: "Capítulos 21–23: tercer ciclo. Job toma la ofensiva y desmonta el sistema de los amigos con datos: los impíos envejecen, se fortalecen, sus casas están en paz, mueren sin dolor y son sepultados con honores (21). Es la misma observación que atormentará a Asaf (Sal 73) y a Jeremías (Jer 12:1). Elifaz, acorralado, cruza la línea final: inventa pecados concretos contra Job —despojó al hermano, negó pan al hambriento, oprimió viudas (22:5-9)— acusaciones que el lector sabe falsas desde el capítulo 1.",
  c: "La prosperidad del impío era un escándalo real en el mundo antiguo, donde la justicia divina se esperaba visible e intrahistórica. Job 21 describe la 'buena muerte' antigua: morir 'en el vigor de su hermosura', con descendencia establecida y sepultura honrosa —todo lo que Job perdió. El capítulo 23 usa de nuevo el lenguaje del tribunal: Job quiere 'llegar hasta su silla', ordenar su causa, llenar su boca de argumentos. Pero el Juez es inhallable: 'he aquí yo iré al oriente, y no lo hallaré; y al occidente, y no lo percibiré' (23:8-9).",
  n: "Job 23:10 es la bisagra: 'mas él conoce mi camino; me probará, y saldré como oro'. Justo cuando confiesa que no puede encontrar a Dios en ninguna dirección, confiesa que Dios sí lo encuentra a él. La fe madura no es ver a Dios; es saberse visto por Él. Y añade su defensa más noble: 'del mandamiento de sus labios nunca me separé; guardé las palabras de su boca más que mi comida' (23:12) — la Palabra como alimento, antes de que existiera un solo libro de la Biblia.",
  p: "El problema de la prosperidad del impío solo se resuelve escatológicamente: la balanza del pacto no se cierra dentro de la historia sino en el juicio final. Asaf lo entendió 'hasta que entré en el santuario de Dios: entonces comprendí el fin de ellos' (Sal 73:17). El pacto de gracia no promete a los creyentes inmunidad temporal, sino herencia eterna; y no promete a los impíos ruina inmediata, sino que 'les está reservada la oscuridad'. Vivir por fe es soportar esa demora sin soltar la promesa (Heb 10:35-39).",
  v: "Thomas Watson: 'Dios prueba a sus hijos como oro; el fuego no destruye el oro, solo consume la escoria'. Calvino sobre 23:10: 'nada se pierde en el horno de Dios sino lo que merecía perderse'. Cf. Sal 73 con el comentario de Spurgeon en 'El tesoro de David'.",
  q: "'Me probará, y saldré como oro.' ¿Puedes decir eso de la prueba que atraviesas ahora, aunque no encuentres a Dios ni al oriente ni al occidente?"
 },
 10: {
  t: "El himno a la sabiduría escondida",
  h: "Capítulos 24–28. El tercer ciclo se desintegra: Bildad apenas balbucea seis versos (25), Zofar ya no habla. El debate humano ha agotado sus municiones sin resolver nada — y ese colapso es deliberado: el autor muestra que la sabiduría de los sabios no alcanza. Entonces, como un interludio musical antes del acto final, llega Job 28: el himno a la sabiduría, una de las cumbres poéticas de toda la literatura universal.",
  c: "Job 28 abre con la descripción más detallada de la minería antigua que poseemos: pozos colgantes donde el hombre oscila lejos de todo pie, ríos desviados, la tierra revuelta 'como por fuego' desde abajo mientras arriba crece el pan. El hombre antiguo ya extraía plata, oro, hierro, cobre, zafiros; llegaba donde ni el halcón ve ni el león pisa. El punto del poema es tremendo: el ser humano, capaz de perforar la roca y vaciar montañas, no puede excavar la Sabiduría. No está en la tierra de los vivientes, no se compra con oro de Ofir.",
  n: "El estribillo estructura el poema: '¿de dónde vendrá la sabiduría, y dónde está el lugar de la inteligencia?' (28:12, 20). La respuesta descarta primero todos los caminos humanos —tecnología, exploración, comercio— y luego da el giro: 'Dios entiende el camino de ella' (28:23). La conclusión ancla todo el libro: 'he aquí que el temor del Señor es la sabiduría, y el apartarse del mal la inteligencia' (28:28). Es exactamente lo que Dios dijo de Job en 1:1,8. Sin saberlo, Job ha descrito su propio tesoro: perdió todo, pero no la sabiduría.",
  p: "Job 28 prepara la respuesta de los capítulos 38–41: si el hombre no puede ni encontrar la sabiduría para gobernar su vida, ¿cómo pretende auditar el gobierno de Dios? Pero el Nuevo Testamento da el paso final: la Sabiduría escondida tiene nombre. 'Cristo, en quien están escondidos todos los tesoros de la sabiduría y del conocimiento' (Col 2:3), 'Cristo poder de Dios, y sabiduría de Dios' (1Co 1:24). Lo que ninguna mina alcanza, Dios lo dio gratis en su Hijo: la sabiduría no se excava; se recibe.",
  v: "Charles Bridges (sobre Proverbios) define el temor del Señor como 'aquella reverencia afectuosa por la cual el hijo se inclina humilde y cuidadosamente a la ley de su Padre'. John Owen: 'la sabiduría de Dios está atesorada en Cristo, y solo en Él se dispensa'.",
  q: "Inviertes esfuerzo de minero en muchas cosas. ¿Excavas con la misma seriedad donde la Sabiduría sí se encuentra?"
 },
 11: {
  t: "La última defensa de Job: memoria, miseria y juramento",
  h: "Capítulos 29–31: el monólogo final de Job, en tres tiempos. Cap. 29: la memoria de su gloria pasada —cuando el Todopoderoso estaba con él, los ancianos se levantaban a su paso y él era 'ojos al ciego y pies al cojo'. Cap. 30: el presente —'y ahora se ríen de mí los más jóvenes que yo'. Cap. 31: el gran juramento de inocencia, la pieza jurídica con la que Job cierra su caso y desafía a Dios a responder: 'aquí está mi firma; respóndame el Todopoderoso' (31:35).",
  c: "Job 29 retrata al anciano noble en la puerta de la ciudad, el tribunal del mundo antiguo: allí se juzgaban pleitos, se rescataba al pobre y se quebraban 'los colmillos del inicuo'. Job 31 sigue el formato del juramento de purificación conocido en el derecho antiguo (cf. el cap. 125 del Libro egipcio de los muertos), pero su ética es revolucionaria: Job no solo jura no haber cometido adulterio, sino haber hecho 'pacto con sus ojos' (31:1); no solo no oprimió a su esclavo, sino que reconoce que 'el que me hizo a mí en el vientre, lo hizo a él' (31:15) — la igualdad radical de amo y siervo ante el Creador, sin paralelo en el mundo antiguo.",
  n: "El juramento de Job 31 es el autorretrato ético más completo del Antiguo Testamento: ojos, corazón, manos, puertas, tierras; adulterio, injusticia laboral, indiferencia al pobre, avaricia, idolatría astral, rencor, hipocresía. Jesús no exigirá menos en el Sermón del Monte; exigirá exactamente esto: pureza desde la raíz del deseo. La ironía trágica: Job tiene razón —es intachable— y precisamente por eso su teología no puede explicar su dolor. Su última palabra es un desafío al cielo. El silencio que sigue ('acaban aquí las palabras de Job') queda vibrando hasta que Dios hable desde el torbellino.",
  p: "Job es el hombre más justo de su generación y aun así necesitará taparse la boca ante Dios (40:4). Ahí está la lección pactual: la mejor justicia humana sirve para el tribunal de los hombres, no para el de Dios. 'Por las obras de la ley ningún ser humano será justificado delante de él' (Ro 3:20). El juramento de Job 31, sublime como es, no puede lo que puede la sangre del Goel de Job 19. Nuestra mejor firma necesita el aval de otra Firma.",
  v: "Thomas Manton: 'el pacto con los ojos es la primera muralla de la castidad'. Matthew Henry sobre 31:1: 'los que quieran guardar el corazón deben guardar los sentidos'. Cf. la Confesión de 1689, cap. 16, sobre las buenas obras: aun las mejores 'no pueden soportar la severidad del juicio de Dios'.",
  q: "Job hizo pacto con sus ojos siglos antes de Mateo 5:28. ¿Qué pactos concretos han hecho tus ojos esta semana?"
 },
 12: {
  t: "Eliú: el joven airado y la pedagogía del sufrimiento",
  h: "Capítulos 32–34. Aparece un personaje nuevo: Eliú, joven, buzita (de la familia de Nacor, hermano de Abraham, Gn 22:21), que ardió en ira 'contra Job porque se justificaba a sí mismo más que a Dios, y contra sus tres amigos porque no hallaban qué responder'. Su discurso —seis capítulos, el más largo del libro— divide a los intérpretes desde antiguo: ¿es un charlatán pomposo o un precursor de la respuesta divina? Nota clave: cuando Dios juzga a los tres amigos (42:7), Eliú no es condenado.",
  c: "Eliú se disculpa por hablar siendo joven: en la cultura antigua la palabra pertenecía a los ancianos ('los días hablarán', 32:7). Su justificación es teológicamente significativa: la sabiduría no viene de la edad sino del 'espíritu que está en el hombre, el soplo del Omnipotente' (32:8). Su aporte central (33): el sufrimiento no es solo retribución (los amigos) ni arbitrariedad (la sospecha de Job); puede ser pedagogía —Dios habla 'una y dos veces' por sueños y por el dolor 'para apartar al hombre de su obra, y quitar del varón la soberbia' (33:14-17).",
  n: "Eliú introduce una figura que nadie había mencionado: el 'mensajero, un intérprete, uno entre mil' que declara al hombre su deber, y el rescate: 'líbralo de descender al sepulcro; yo he hallado redención (kofer, precio de rescate)' (33:23-24). Entonces el hombre ora, Dios le restaura y confiesa: 'pequé... y no me fue provechoso; Dios redimirá mi alma del sepulcro' (33:27-28). Es el esquema completo del evangelio en miniatura: mediador, rescate, confesión, restauración, luz. El joven airado ve más lejos que los tres ancianos.",
  p: "La doctrina del sufrimiento como disciplina paternal que Eliú esboza florece en el nuevo pacto: 'el Señor al que ama, disciplina... Dios os trata como a hijos' (Heb 12:5-11). Bajo el pacto de gracia ningún dolor del creyente es castigo judicial —ese cayó entero sobre el Fiador— sino cincel del Padre. Y el 'rescate hallado' de 33:24 tiene nombre: 'el Hijo del Hombre vino... para dar su vida en rescate (lytron) por muchos' (Mr 10:45). Dios no dice dónde halló el rescate; el Calvario lo revela.",
  v: "John Owen sobre Hebreos 12: la disciplina es privilegio de hijos, no ira de juez. Thomas Brooks: 'las aflicciones son el correo por el que Dios envía sus mejores misericordias'. Joseph Caryl dedica páginas luminosas al 'intérprete, uno entre mil'.",
  q: "¿Lees tus aflicciones como multas de un juez o como cartas de un Padre? La diferencia es todo el evangelio."
 },
 13: {
  t: "Dios en la tormenta que se acerca",
  h: "Capítulos 35–37: Eliú concluye. Corrige primero un dicho de Job ('¿qué provecho tengo de no haber pecado?', 35:3): tu pecado o tu justicia no le añaden ni quitan nada a Dios —pero sí a tus prójimos (35:6-8). Luego amplía su teología de la disciplina (36) y termina con un majestuoso poema de la tormenta (36:26–37:24): truenos, relámpagos, nieve, torbellino. Mientras habla, parece que la tempestad real se va formando en el horizonte: cuando Eliú calla, 'Jehová respondió a Job desde un torbellino' (38:1).",
  c: "Para el hombre antiguo la tormenta era teofanía por excelencia: Baal era el 'jinete de las nubes' en Ugarit. La Escritura reclama esa imaginería para el Dios vivo: Él truena con voz maravillosa, dice a la nieve 'desciende a la tierra', sella la mano de todo hombre para que reconozca su obra (37:5-7). La meteorología de Eliú es doxología: el ciclo del agua (36:27-28), la física de las nubes ('¿sabes tú el equilibrio de las nubes?', 37:16) —todo se convierte en argumento de la grandeza incomprensible de Dios.",
  n: "Función narrativa de Eliú: es el puente entre el debate humano y la voz divina. Baja la mirada de Job desde su caso hacia el cosmos, preparándolo para el interrogatorio de Dios. Su última frase es el umbral: 'Él es Todopoderoso, al cual no alcanzamos... teman delante de él los hombres; él no estima a ninguno que cree en su propio corazón que es sabio' (37:23-24). El escenario está listo. El hombre ha dicho todo lo que el hombre puede decir. Ahora hablará el torbellino.",
  p: "'He aquí, Dios es grande, y nosotros no le conocemos' (36:26). Eliú enseña lo que la teología llama la incomprensibilidad de Dios: lo conocemos verdaderamente (porque se revela) pero no exhaustivamente (porque es infinito). Esta es la humildad epistemológica del pacto: el Dios que no podemos abarcar se ha dado a conocer suficientemente en su Palabra y finalmente en su Hijo (Jn 1:18). No sabemos todos los porqués; sabemos con Quién estamos pactados. Y eso basta para atravesar cualquier tormenta — dentro de la cual, aprenderá Job, no hay caos sino un trono.",
  v: "La Confesión de 1689, cap. 2: Dios es 'infinito en ser y perfección, cuya esencia no puede ser comprendida por nadie sino por él mismo'. Stephen Charnock, 'La existencia y atributos de Dios', desarrolla esta gloria. Calvino: 'toda recta sabiduría consiste en conocer a Dios y conocernos a nosotros mismos'.",
  q: "¿Necesitas entender a Dios para confiar en Él, o confiar en Él para empezar a entenderlo?"
 },
 14: {
  t: "La voz del torbellino: el zoológico de Dios",
  h: "Capítulos 38–39: por fin, Dios responde. Pero no responde nada de lo que se debatió durante 35 capítulos: ni una palabra sobre la apuesta del acusador, ni sobre los pecados hipotéticos de Job, ni sobre la retribución. En cambio: un interrogatorio de más de 70 preguntas sin respuesta posible. '¿Dónde estabas tú cuando yo fundaba la tierra? Házmelo saber, si tienes inteligencia' (38:4). Cosmología, meteorología, astronomía, zoología: cimientos, mar, aurora, nieve, Pléyades y Orión, leona, cuervo, cabras monteses, asno montés, búfalo, avestruz, caballo de guerra, halcón, águila.",
  c: "El género del interrogatorio sapiencial existía en Egipto (el maestro humillaba al alumno arrogante con preguntas imposibles), pero aquí el maestro es el Creador. Nota qué criaturas elige Dios: casi ninguna útil al hombre. El asno montés que se ríe de la ciudad, el búfalo que no acepta yugo, la avestruz absurda y veloz, el águila en la peña inaccesible. Dios se deleita en criaturas salvajes, inútiles, libres —un universo que no gira alrededor del ser humano ni de su economía. Para el antiguo (y el moderno) utilitarismo, esto es una revolución: la creación existe primero para el gozo de su Creador.",
  n: "La estrategia divina es aparentemente extraña pero perfecta: en lugar de explicarle a Job su caso, le muestra el mundo. Es un cambio de escala: si el gobierno de Dios sobre la aurora, la lluvia 'en tierra donde no hay hombre' (38:26) y el parto de las ciervas es tan vasto, sabio y detallado, ¿no será igual de sabio su gobierno sobre el dolor de Job, aunque igual de inescrutable? Dios no le da a Job información sino perspectiva; no un argumento sino una visión. Y con ternura irónica: 'tú lo sabes, pues entonces ya habías nacido' (38:21).",
  p: "La respuesta del torbellino enseña la doctrina de la providencia en su forma más pura: Dios gobierna todas las cosas, desde las Pléyades hasta el polluelo del cuervo, con sabiduría que no rinde cuentas y bondad que no necesita auditoría. Para el creyente del pacto, esta providencia tiene rostro: 'vuestro Padre celestial las alimenta' (Mt 6:26); ni un pajarillo cae a tierra sin Él (Mt 10:29). Lo que Job vio en el zoológico salvaje, nosotros lo leemos con una palabra más dulce: Padre.",
  v: "La Confesión de 1689, cap. 5: 'Dios, el buen Creador de todas las cosas, en su infinito poder y sabiduría sostiene, dirige, dispone y gobierna a todas las criaturas'. John Flavel, 'El misterio de la providencia': 'la providencia es como las palabras hebreas: solo se lee bien hacia atrás'.",
  q: "Dios riega tierras donde no hay ningún hombre que lo vea (38:26). ¿Puedes adorar a un Dios que hace cosas gloriosas que nadie aplaude ni entiende?"
 },
 15: {
  t: "Behemot, Leviatán y el polvo que adora",
  h: "Capítulos 40–42: el desenlace. Primera rendición de Job ('he aquí que yo soy vil... mi mano pongo sobre mi boca', 40:4), segundo discurso divino con las dos criaturas colosales —Behemot y Leviatán—, la retractación final ('de oídas te había oído; mas ahora mis ojos te ven; por tanto me aborrezco, y me arrepiento en polvo y ceniza', 42:5-6), el veredicto contra los amigos, la intercesión de Job por ellos y la restauración doblada: 140 años más, nueva familia, y sus hijas —caso extraordinario en el mundo antiguo— reciben herencia junto a sus hermanos.",
  c: "Behemot y Leviatán han sido leídos como hipopótamo y cocodrilo, pero el lenguaje los desborda (Leviatán respira fuego, 41:19-21). En la literatura cananea, Lotan/Leviatán era el monstruo del caos vencido por los dioses; la Escritura usa esa imaginería para declarar que hasta el caos máximo es criatura de Dios, su 'juguete' (41:5; cf. Sal 104:26). El mensaje para Job: hay fuerzas en el universo que tú no puedes domar —el mal incluido— pero ninguna que Dios no tenga de correa, como viste en los capítulos 1–2 sin saberlo.",
  n: "El final resuelve con maestría lo que no explica: Job nunca sabe del telón celestial, y sin embargo queda satisfecho —porque su problema real no era la falta de información sino la aparente ausencia de Dios, y ahora 'mis ojos te ven'. El veredicto divino es la sorpresa suprema: 'no habéis hablado de mí lo recto, como mi siervo Job' (42:7, dos veces). Los defensores de Dios, condenados; el litigante quejoso, aprobado. La queja dirigida a Dios en fe honra a Dios más que la teología correcta usada sin amor. Y la restauración llega cuando Job ora por quienes lo hirieron.",
  p: "Job termina como sombra del Mediador: los culpables son perdonados mediante el sacrificio que ofrece y la intercesión del justo agraviado (42:8-10). Así Cristo: 'Padre, perdónalos'. Santiago 5:11 sella la lectura pactual: 'el fin del Señor' muestra que es 'muy misericordioso y compasivo'. El libro entero enseña que el pacto sostiene cuando la explicación falta: Dios puede ser adorado en la ruina, el acusador refutado, y el sufrimiento del justo convertido en gloria. Todo ello, a escala infinita, es la cruz.",
  v: "Spurgeon: 'de oídas a vista: esa es toda la diferencia entre religión y comunión'. Thomas Watson: 'la oración de Job por sus amigos abrió la puerta de su propia libertad'. Joseph Caryl cierra sus 24 años de exposición: 'el fin del Señor es mejor que el principio'.",
  q: "¿Conoces a Dios de oídas —sermones, libros, opiniones ajenas— o tus ojos lo han visto en su Palabra hasta arrepentirte en polvo y ceniza?"
 },
 16: {
  t: "El llamado de Abram: el pacto que sostiene la Biblia entera",
  h: "Volvemos a Génesis. Estamos alrededor del 2000 a.C. Abram vive en Ur de los caldeos, una de las ciudades más avanzadas del mundo: zigurat monumental, escritura, comercio internacional, y culto al dios-luna Sin. Josué 24:2 es explícito: la familia de Abram 'servía a dioses extraños'. Dios no eligió a un buscador espiritual; irrumpió en la vida de un idólatra. La ruta Ur–Harán–Canaán sigue el corredor fértil de las caravanas; Harán era también centro del culto lunar, lo que explica la escala familiar allí.",
  c: "En Génesis 15 Dios 'corta' pacto con Abram mediante un rito documentado en tratados antiguos: los animales partidos y el paso entre las mitades significaban una automaldición ('que me hagan como a estos animales si rompo el pacto'). Lo inaudito del texto: solo Dios —horno humeante y antorcha de fuego— pasa entre los pedazos, mientras Abram duerme. Dios asume ambas partes del compromiso: la promesa y la maldición por el incumplimiento. Es la definición visual del pacto de gracia: Dios jura cargar Él mismo la maldición. En el Calvario, la cargó.",
  n: "La estructura de Génesis 12:1-3 responde a Babel punto por punto: ellos quisieron hacerse un nombre; Dios dice 'engrandeceré tu nombre'. Ellos temían dispersarse; en Abram 'serán benditas todas las familias de la tierra'. El relato es honesto con su héroe: apenas llega a Canaán, el hambre lo empuja a Egipto donde miente sobre Sara —y Dios lo rescata de su propia cobardía. El pacto no depende de la firmeza del patriarca sino de la fidelidad del que juró. Génesis 15:6 es el versículo eje: 'y creyó a Jehová, y le fue contado por justicia'.",
  p: "Pablo construye la doctrina de la justificación sobre Génesis 15:6 (Ro 4; Gá 3): Abram fue declarado justo por creer la promesa, antes de la circuncisión, antes de la ley, antes de toda obra. El pacto abrahámico contiene el evangelio anticipado ('en ti serán benditas todas las naciones', Gá 3:8) y apunta a la Simiente singular, Cristo (Gá 3:16). La teología bautista pactual subraya: la promesa salvífica del pacto abrahámico se cumple en Cristo y su pueblo creyente —'los que son de fe, estos son hijos de Abraham' (Gá 3:7).",
  v: "Nehemiah Coxe: 'el pacto con Abraham contenía la promesa del evangelio, y en ella estaba envuelto Cristo'. Calvino sobre Gn 15:17: 'Dios se dignó descender hasta hacerse deudor de su propia promesa'. Matthew Henry: 'Abram salió sin saber a dónde iba, pero sabiendo con quién iba'.",
  q: "Abram dejó lo seguro por una promesa sin mapa. ¿Qué te pide Dios soltar hoy sin más garantía que su Palabra — y no es su Palabra la mayor garantía?"
 },
 17: {
  t: "Agar, la circuncisión y el Huésped de Mamre",
  h: "Génesis 16–18. Diez años esperando la promesa, y Sara ofrece a Abram su sierva egipcia Agar. La maniobra era legal y corriente: los contratos de Nuzi y el código de Hammurabi contemplan que la esposa estéril dé su esclava como vientre sustituto. Todo perfectamente cultural — y perfectamente incrédulo. Ismael nace de la ley y la costumbre; Isaac nacerá del milagro y la promesa. En el cap. 17, trece años después, Dios reaparece, cambia los nombres (Abram→Abraham, Sarai→Sara) e instituye la circuncisión como señal del pacto.",
  c: "La circuncisión existía en otros pueblos (Egipto la practicaba en adolescentes o novios), pero Dios la resignifica: al octavo día, en la carne del órgano de la descendencia, marcando que la simiente prometida vendría por gracia divina y no por potencia humana. La hospitalidad de Génesis 18 —correr al encuentro, agua para los pies, el becerro tierno— es el protocolo beduino pleno; lo asombroso es el Huésped: 'apareció Jehová' en forma de tres varones. Abraham regatea por Sodoma como en un zoco oriental, de 50 a 10 justos, y descubre que la misericordia de Dios aguanta más regateo del que el intercesor se atreve a pedir.",
  n: "El ángel de Jehová encuentra a Agar en el desierto (16): primera aparición del 'ángel de Jehová' en la Biblia, y es para una esclava egipcia maltratada y embarazada. Ella le pone nombre a Dios —'Tú eres Dios que ve' (El Roí)— única persona en el AT que lo hace. El Dios del pacto ve a los invisibles. En el cap. 17, Abraham se ríe (17:17); en el 18, Sara se ríe; el hijo se llamará Isaac, 'él ríe': Dios inscribe la risa incrédula de ambos en el nombre del milagro, transformándola en risa de gozo (21:6).",
  p: "Pablo lee Agar/Sara alegóricamente (Gá 4:21-31): dos pactos, el que engendra esclavos según la carne y el de la promesa que engendra libres. La circuncisión, enseña la teología bautista pactual, era señal del pacto abrahámico en su administración nacional-tipológica; su verdad interior era 'la circuncisión del corazón' (Dt 30:6; Ro 2:29). En el nuevo pacto la señal —el bautismo— se aplica a los que profesan la realidad interior: nacidos no 'de voluntad de carne' sino de Dios. Y Génesis 18:25 queda como roca de la teodicea: 'el Juez de toda la tierra, ¿no ha de hacer lo que es justo?'.",
  v: "Nehemiah Coxe distingue con cuidado la promesa espiritual y la administración carnal del pacto abrahámico — el corazón del argumento bautista reformado. Benjamin Keach sobre las señales del pacto. Matthew Henry: 'Dios vino a Agar cuando nadie más vino'.",
  q: "Sara usó métodos legítimos de su cultura para 'ayudar' a la promesa. ¿Dónde estás fabricando un Ismael en lugar de esperar un Isaac?"
 },
 18: {
  t: "Sodoma, Lot y el nacimiento de la risa",
  h: "Génesis 19–21. La destrucción de Sodoma y Gomorra quedó grabada como paradigma de juicio en toda la Escritura (Is 1; Ez 16; Lc 17; 2P 2; Jud). Las ciudades se ubicaban en la cuenca del mar Muerto, zona de betún, azufre y actividad sísmica —los materiales del juicio estaban bajo sus pies. El cap. 20 repite el ardid de Abraham ('es mi hermana') ahora en Gerar, con el rey filisteo Abimelec; y en el 21, veinticinco años después de la promesa, nace Isaac 'al tiempo que Dios le había dicho'.",
  c: "El deber de hospitalidad hace legible el horror de Génesis 19: Lot ofrece su casa y protección a los visitantes; toda la ciudad, 'desde el más joven hasta el más viejo', exige violarlos. La depravación de Sodoma es total: violencia sexual, desprecio del forastero, y según Ezequiel 16:49, 'soberbia, saciedad de pan y abundancia de ociosidad' sin fortalecer 'la mano del afligido'. La mujer de Lot, cristalizada por mirar atrás, se volvió advertencia proverbial: 'acordaos de la mujer de Lot' (Lc 17:32). Las hijas de Lot, engendrando a Moab y Amón de su padre, muestran que sacaron Sodoma de la ciudad aunque salieron de ella.",
  n: "El contraste estructural es deliberado: Abraham en la cumbre intercediendo al amanecer (19:27-28) mientras el humo sube como de un horno; Lot, el hombre que eligió por la vista (13:10), perdiéndolo todo, titubeando hasta que los ángeles lo sacan a rastras 'según la misericordia de Jehová para con él' (19:16). Pedro lo llama 'justo Lot' (2P 2:7-8): un creyente real, carnal y arruinado, salvado 'así como por fuego'. Y el hilo de oro: 'se acordó Dios de Abraham, y envió fuera a Lot' (19:29) — la intercesión del amigo de Dios salvó al vacilante.",
  p: "Sodoma establece el patrón bíblico del juicio escatológico: fuego repentino sobre la seguridad carnal, rescate del remanente justo, prohibición de mirar atrás (Lc 17:28-33). El nacimiento de Isaac establece el patrón opuesto: la vida que Dios da al cuerpo 'ya como muerto' (Ro 4:19), tipo de todo nacimiento espiritual y, en última instancia, de la resurrección. Toda la existencia del pueblo de Dios cuelga de un poder que hace reír: 'Dios me ha hecho reír' (21:6). La gracia siempre llega como imposible cumplido.",
  v: "Thomas Watson: 'la mujer de Lot pereció mirando lo que Dios quemaba'. John Bunyan hizo de Sodoma el retrato de la Ciudad de Destrucción. Matthew Henry sobre 19:16: 'la salvación de Lot fue con demoras del hombre y violencia de la misericordia'.",
  q: "Lot 'se detenía' mientras ardía el plazo (19:16). ¿Hay misericordias de Dios que están tirando de tu mano mientras tú miras hacia atrás?"
 },
 19: {
  t: "Moriah: el sacrificio pedido y el sacrificio provisto",
  h: "Génesis 22–24: la cima del ciclo de Abraham. 'Toma ahora tu hijo, tu único, Isaac, a quien amas...' — la primera vez que la palabra 'amor' aparece en la Biblia es un padre entregando a su hijo. El monte Moriah será, siglos después, el emplazamiento del templo de Salomón (2Cr 3:1): todos los sacrificios de Israel se ofrecerían donde Abraham aprendió que 'Jehová proveerá'. El cap. 23 registra la compra de la cueva de Macpela —único terreno que Abraham poseyó de toda la tierra prometida— y el 24, el encargo del siervo para hallar esposa a Isaac.",
  c: "El sacrificio de niños existía en Canaán y Fenicia; la orden inicial no habría sonado impensable en el entorno de Abraham — precisamente por eso la conclusión es revolucionaria: el Dios de Abraham detiene el cuchillo y provee sustituto. Israel aprendió en su texto fundacional que su Dios no quiere hijos quemados sino fe obediente, y que Él mismo provee el cordero. La negociación por Macpela (23) es una escena hitita/oriental clásica: cortesías floridas ('escúchanos, señor nuestro; eres un príncipe de Dios'), regalo aparente y precio pleno pagado ante testigos en la puerta: 400 siclos pesados 'de buena ley'.",
  n: "Génesis 22 es sobriedad narrativa perfecta: tres días de camino de los que no se dice palabra, el leño sobre los hombros del hijo, la pregunta que parte el alma ('¿dónde está el cordero?') y la respuesta que sostiene la Biblia entera: 'Dios se proveerá de cordero'. Hebreos 11:19 revela el razonamiento de la fe de Abraham: 'pensó que Dios es poderoso para levantar aun de entre los muertos'. La fe no fue ausencia de lógica sino lógica fundada en la promesa: si Dios prometió descendencia en Isaac, y pide a Isaac, entonces Dios resucita.",
  p: "Moriah es el tipo supremo del Calvario: el padre que entrega a su único hijo amado, el hijo que carga el madero y obedece, el monte de Jerusalén, el sustituto trabado en el zarzal con espinas en la cabeza. Con una diferencia que es todo el evangelio: a Abraham se le devolvió el hijo; el Padre celestial 'no escatimó ni a su propio Hijo, sino que lo entregó por todos nosotros' (Ro 8:32, eco directo de Gn 22:12,16). El juramento de Dios en 22:16-18 es, según Hebreos 6:13-18, el ancla de nuestra alma: dos cosas inmutables, promesa y juramento.",
  v: "John Owen: 'en Moriah, la fe de Abraham y el evangelio de Dios se encontraron cara a cara'. Spurgeon sobre 'Jehová-jireh': 'en el monte del Señor será provisto — llega al monte y encontrarás la provisión'. Matthew Henry: 'Dios probó a Abraham, no para saber, sino para mostrar'.",
  q: "Dios pidió lo único que a Abraham le importaba más que todo. ¿Sabe tu corazón, por experiencia, que quien devuelve es el mismo que pide?"
 },
 20: {
  t: "Dos naciones en un vientre: Esaú, Jacob y la elección",
  h: "Génesis 25–26. Muere Abraham a los 175 años; Isaac hereda promesa y pozos. Rebeca, estéril veinte años, concibe mellizos tras la oración de Isaac, y la respuesta divina al embarazo turbulento define la teología de los siguientes mil años: 'dos naciones hay en tu seno... y el mayor servirá al menor' (25:23). Edom (Esaú) e Israel (Jacob) pelearán durante toda la historia bíblica. El cap. 26 es el único dedicado enteramente a Isaac: hambre, la vieja mentira familiar en Gerar, pozos reabiertos y disputados, y la renovación del pacto jurado a Abraham.",
  c: "La primogenitura en el mundo antiguo implicaba doble porción de herencia y jefatura del clan; los documentos de Nuzi muestran que podía venderse o transferirse —el trueque de Esaú era legalmente válido y moralmente revelador. El guiso rojo por el derecho sagrado: 'así menospreció Esaú la primogenitura' (25:34). Los pozos del cap. 26 eran vida o muerte en el Néguev: reabrir los pozos del padre y ponerles los mismos nombres (26:18) era reclamar herencia y continuidad. Isaac, el patriarca 'menor', brilla precisamente en la paciencia: cavar, ceder, volver a cavar, hasta Rehobot: 'ahora Jehová nos ha prosperado'.",
  n: "El narrador retrata a los mellizos con trazos precisos: Esaú, hombre del campo, inmediato, gobernado por el estómago y el impulso ('dame de comer... he aquí yo me voy a morir'); Jacob, 'varón quieto que habitaba en tiendas', calculador, agarrado al talón desde el vientre. Ninguno es ejemplar: uno desprecia lo santo, el otro lo codicia con métodos torcidos. La gracia no encontrará material noble en Jacob; lo fabricará a golpes de Peniel. Nota también la disfuncionalidad sembrada: 'Isaac amó a Esaú... mas Rebeca amaba a Jacob' (25:28) — el favoritismo parental que cosechará engaño y exilio.",
  p: "Pablo apela a este pasaje para la doctrina de la elección: 'no habiendo aún nacido, ni hecho aún ni bien ni mal... le fue dicho: el mayor servirá al menor' (Ro 9:10-13). La elección no se funda en obras previstas sino en 'el propósito de Dios conforme a la elección'. Hebreos 12:16-17 usa a Esaú como advertencia pastoral: el 'profano' que vendió lo eterno por lo inmediato y después no halló lugar para el arrepentimiento. Entre ambos textos queda el misterio adorable: la gracia escoge sin méritos y el que desprecia lo santo es responsable de su desprecio.",
  v: "La Confesión de 1689, cap. 3: la elección es 'sin ninguna otra cosa en la criatura como condición o causa que lo mueva a ello'. Thomas Watson: 'Esaú tuvo el guiso y perdió la bendición; el mundo alimenta y desengaña'. Calvino sobre Ro 9 sigue de cerca este pasaje.",
  q: "¿Qué 'guiso rojo' —inmediato, caliente, disponible— te tienta a malbaratar lo que Dios llama santo y eterno?"
 },
 21: {
  t: "La bendición robada y la escalera de Betel",
  h: "Génesis 27–29. Isaac, viejo y ciego, decide bendecir a Esaú contra el oráculo de 25:23; Rebeca y Jacob montan el engaño de las pieles de cabrito; Esaú jura matar a su hermano, y Jacob huye 900 km hasta Harán, la tierra de su madre. En el camino, Betel: el sueño de la escalera. En Harán, el engañador es engañado: sirve siete años por Raquel y amanece casado con Lea —'¿por qué, pues, me has engañado?' (29:25), pregunta el hombre de las pieles de cabrito, y el lector saborea la ironía de la justicia poética divina.",
  c: "La bendición patriarcal era un acto jurídico-performativo irrevocable, como muestran los paralelos de Nuzi: pronunciada, quedaba pronunciada ('yo le bendije, y será bendito', 27:33). La escalera de Betel evoca la rampa del zigurat —el 'vínculo cielo-tierra' que Babel intentó construir desde abajo—, pero aquí desciende desde arriba y Dios está de pie junto al fugitivo. El matrimonio con velo (Lea entregada de noche), la semana nupcial que debía completarse (29:27) y el servicio como precio nupcial (mohar) son costumbres arameas bien documentadas. Labán, con contratos siempre torcidos a su favor, es el retrato del patriarcalismo mercantil de Harán.",
  n: "El narrador no blanquea a nadie: Isaac bendice guiado por el paladar, Rebeca manipula, Jacob miente tres veces (llegando a decir 'Jehová tu Dios me la dio', 27:20), Esaú se victimiza. Y sin embargo 'la bendición' viaja por en medio del lodo humano exactamente adonde Dios dijo. Betel es la escena decisiva: al fugitivo con una piedra por almohada, que no buscó a Dios ni lo esperaba, Dios le repite entera la promesa abrahámica y añade la palabra personal: 'he aquí, yo estoy contigo, y te guardaré por dondequiera que fueres' (28:15). La respuesta de Jacob todavía regatea: 'si Dios fuere conmigo...' (28:20). La gracia empieza con nosotros mucho antes de que nosotros empecemos con ella.",
  p: "Jesús se declara la escalera de Betel: 'veréis el cielo abierto, y a los ángeles de Dios que suben y descienden sobre el Hijo del Hombre' (Jn 1:51). Él es el único vínculo entre el cielo y la tierra, puesto por Dios, no construido por el hombre. Y la historia de la bendición enseña la doctrina que Pablo formula en Ro 9:16: 'no depende del que quiere, ni del que corre, sino de Dios que tiene misericordia' — aunque los métodos carnales de Rebeca y Jacob no queden sin cosecha: veinte años de exilio, engaños de Labán y el luto de una madre que nunca volvió a ver a su hijo.",
  v: "Matthew Henry sobre Betel: 'Cristo es esta escalera; su naturaleza humana el pie en la tierra, su divina la cúspide en el cielo'. Thomas Boston predicó sobre el 'si' de Jacob como fe en embrión. John Gill nota que la promesa 'no te dejaré' de 28:15 reaparece en Heb 13:5 para todo creyente.",
  q: "Dios se apareció a Jacob cuando huía con las manos sucias. ¿Crees que Dios solo se encuentra contigo cuando llegas limpio, o el evangelio dice otra cosa?"
 },
 22: {
  t: "Los años de Labán: el crisol del engañador",
  h: "Génesis 30–31. Veinte años en Harán: catorce sirviendo por dos esposas, seis por el ganado (31:41). El hogar de Jacob es un campo de batalla: dos hermanas rivales contando hijos como trofeos, dos siervas convertidas en vientres sustitutos, mandrágoras negociadas por noches conyugales. De ese caos —celos, poligamia, superstición— nacen los doce patriarcas de Israel. Al final, Dios ordena el regreso (31:3), Jacob huye con familia y rebaños, Labán lo persigue, y ambos cortan alianza en el mizpa de Galaad: frontera definitiva entre el arameo y el hebreo.",
  c: "Las mandrágoras (30:14) eran consideradas afrodisíacas y fecundantes en todo el antiguo Oriente —superstición que el relato desmiente con ironía: Raquel, que las compró, siguió estéril hasta que 'se acordó Dios de Raquel' (30:22). Las prácticas de cría selectiva de Jacob (varas descortezadas) mezclan folclore ganadero con lo que Jacob después confiesa como pura intervención divina (31:9-12). Los 'terafines' que Raquel roba eran ídolos domésticos vinculados, según los textos de Nuzi, a derechos de herencia —de ahí la furia de Labán. Raquel sentada sobre los dioses de su padre, alegando impureza menstrual, es la sátira más mordaz de la idolatría en Génesis: dioses sobre los que una mujer se sienta.",
  n: "El narrador teje la ironía moral: el que compró la primogenitura con guiso y robó la bendición con pieles, es esquilmado con salarios cambiados 'diez veces' (31:7). En el espejo de Labán, Jacob contempla su propio rostro. Pero en el crisol algo cambia: el Jacob que sale de Harán habla de Dios de otra manera —'el Dios de mi padre ha estado conmigo' (31:5), 'vio Dios mi aflicción y el trabajo de mis manos' (31:42). El pleito final ante los rebaños es su primera declaración de integridad verificable: veinte años de trabajo honesto bajo sol y helada. Dios estaba puliendo al engañador mediante un engañador mayor.",
  p: "La historia enseña la providencia santificadora: Dios usa a Labán como lija para Jacob, igual que usará a Egipto para Israel y la espina para Pablo. Nada del caos familiar frustra el plan: de Lea la no amada nacen Leví (el sacerdocio) y Judá (la realeza y el Mesías). Dios escribe derecho con renglones torcidos, no porque los renglones no importen, sino porque su gracia es mayor que nuestra torcedura. 'El Dios de Betel' (31:13) se identifica por el lugar de la promesa: el pacto hecho al fugitivo gobierna los veinte años de exilio.",
  v: "John Flavel: 'la providencia usa muelas ásperas para afilar a sus santos'. Matthew Henry: 'Lea, la menos amada del marido, fue la más honrada por Dios: madre del sacerdote y del Rey'. Thomas Watson sobre la aflicción como 'medicina de Dios'.",
  q: "¿Reconoces a tu 'Labán' —esa persona o circunstancia áspera— como herramienta con la que Dios está desbastando tu viejo carácter?"
 },
 23: {
  t: "Peniel: el hombre que venció siendo derrotado",
  h: "Génesis 32–34. Jacob regresa y le espera lo que más teme: Esaú, con 400 hombres. La noche antes del encuentro, en el vado de Jaboc, ocurre el episodio más enigmático de Génesis: 'luchó con él un varón hasta que rayaba el alba'. Jacob sale con nombre nuevo —Israel, 'porque has luchado con Dios y con los hombres, y has vencido'— y con la cadera dislocada. El encuentro con Esaú resulta desconcertantemente tierno: 'corrió Esaú a su encuentro, y le abrazó... y lloraron' (33:4). El cap. 34, en cambio, es el horror de Siquem: Dina violada, y la venganza a traición de Simeón y Leví usando la señal del pacto como trampa.",
  c: "Los vados de los ríos eran, en la imaginación antigua, lugares de encuentros numinosos y de emboscadas: cruzar un río de noche era cruzar una frontera espiritual. El cambio de nombre por parte de una deidad o un rey significaba nueva identidad y nuevo destino (Abram→Abraham; luego Oseas→Josué, Simón→Pedro). Los regalos escalonados de Jacob a Esaú (32:13-21) siguen el protocolo diplomático de apaciguamiento del antiguo Oriente: literalmente dice 'cubriré su rostro con el presente... quizá levante mi rostro' — lenguaje de expiación. En Siquem, la propuesta de matrimonio con precio (34:12) y la circuncisión como condición de alianza tribal eran negociaciones reconocibles; el abuso de la señal sagrada para masacrar es lo que el texto (y Jacob en 49:5-7) condena.",
  n: "La lucha de Jaboc es la biografía de Jacob condensada: toda su vida ha luchado —con Esaú desde el vientre, con Isaac por la bendición, con Labán por el salario— agarrando, suplantando, negociando. Ahora lucha con Dios mismo y aprende la paradoja final: se vence a Dios no derrotándolo sino aferrándose a Él después de ser quebrantado. 'No te dejaré, si no me bendices' — dicho por un hombre que ya no puede ni sostenerse en pie. Oseas 12:4 lo interpreta: 'venció al ángel, y prevaleció; lloró, y le rogó'. Su victoria fue una súplica con lágrimas. Y amanece cojeando hacia Esaú: indefenso por primera vez, y por primera vez a salvo.",
  p: "Peniel ('vi a Dios cara a cara, y fue librada mi alma') es el retrato de la oración que prevalece: la fe que se agarra de Dios contra Dios, de la promesa contra la apariencia —como la cananea de Mateo 15. El Varón que luchó es leído por muchos (con Calvino y la tradición) como el Ángel de Jehová, el Hijo preencarnado: el mismo que un día se dejará vencer del todo, no dislocando nuestra cadera sino siendo Él traspasado. Dios hiere a Jacob para bendecirlo: la cojera es el sacramento permanente de su nueva fuerza. Los Israel de Dios cojean.",
  v: "Charles Wesley volcó Peniel en su himno '¡Ven, oh Viajero desconocido!' que Spurgeon llamó la cumbre de la himnodia. Matthew Henry: 'Jacob nunca caminó tan derecho como cuando empezó a cojear'. John Knox, se decía, 'luchaba con Dios' así por Escocia.",
  q: "¿Ha tocado Dios tu 'cadera' —el punto de tu fuerza natural— para enseñarte a colgarte solo de Él? ¿Qué sería para ti orar 'no te dejaré si no me bendices'?"
 },
 24: {
  t: "De Betel a la cisterna: muerte de Raquel y venta de José",
  h: "Génesis 35–37. Dios manda a Jacob subir a Betel, cerrando el círculo abierto en la huida: allí purifica su casa de dioses extraños (los terafines viajaban aún en el equipaje) y Dios le confirma el nombre Israel y la promesa. En el camino muere Raquel dando a luz a Benjamín, cerca de Belén —su tumba era hito conocido en tiempos de Samuel (1S 10:2) y Jeremías la hizo símbolo del llanto de la nación (Jer 31:15, citado en Mt 2:18). Muere también Isaac, y el cap. 36 despacha la genealogía de Esaú/Edom. Con el 37 empieza la historia de José: la túnica, los sueños, la cisterna y la caravana a Egipto.",
  c: "Enterrar los ídolos y los zarcillos bajo la encina de Siquem (35:4) era un rito de ruptura: los amuletos-aretes tenían función mágica. La 'túnica de diversos colores' (o de mangas largas, ketonet passim) marcaba exención del trabajo y estatus de heredero —la misma palabra describe el vestido real de Tamar, hija de David (2S 13:18). Las cisternas secas eran las cárceles improvisadas del mundo pastoril (cf. Jeremías en Jer 38:6). La caravana ismaelita/madianita con 'aromas, bálsamo y mirra' recorría la ruta comercial de Galaad a Egipto; veinte piezas de plata era el precio corriente de un esclavo joven en el segundo milenio a.C. — los detalles del relato huelen a época exacta.",
  n: "El ciclo de José se abre con el mecanismo que gobernará trece capítulos: los sueños dobles y el odio que provocan. Nota la cadena de causas bajas: el favoritismo de Jacob (la túnica), el chisme de José (37:2), la envidia de los hermanos, la frialdad del negocio de Judá ('¿qué provecho...? vendámosle'). Y la escena más cruel del Génesis: comen pan sentados junto a la cisterna donde su hermano suplica (37:25; cf. 42:21). El engañador Jacob es engañado con las herramientas de su propio pasado: un cabrito (como las pieles ante Isaac) y una prenda de vestir (como la ropa de Esaú). La siega moral es exacta.",
  p: "Aquí arranca la más nítida figura de Cristo del Antiguo Testamento: el hijo amado del padre, enviado a sus hermanos, despojado de su túnica, vendido por piezas de plata por consejo de Judá (¡Judá/Judas!), contado como muerto y destinado —a través del pozo— al trono que salvará al mundo. Y sobre toda la maquinaria del mal, la mano invisible que José confesará al final: 'vosotros pensasteis mal contra mí, mas Dios lo encaminó a bien' (50:20). Hechos 2:23 dirá lo mismo de la cruz: entregado 'por el determinado consejo y anticipado conocimiento de Dios', y crucificado 'por manos de inicuos'. Soberanía y responsabilidad, sin mezcla y sin excusa.",
  v: "Thomas Watson: 'Dios convierte el veneno de la envidia en medicina para su iglesia'. Matthew Henry ve en Raquel muriendo al dar vida ('Benoni/Benjamín': hijo de mi dolor/hijo de la diestra) una sombra del fruto que nace del dolor. John Flavel sobre la providencia en la caravana que pasó 'justo entonces'.",
  q: "Los hermanos comieron tranquilos junto al pozo del que subía el llanto de José. ¿A qué clamor cercano te has vuelto sordo por envidia, comodidad o rencor?"
 },
 25: {
  t: "Judá y Tamar, José y la casa de Potifar: dos hombres ante la tentación",
  h: "Génesis 38–40. El narrador interrumpe la historia de José para contar el escándalo de Judá y Tamar (38): los hijos malvados, la viuda burlada dos veces, el disfraz junto al camino, el sello, el cordón y el bastón como prueba, y el veredicto que Judá pronuncia contra sí mismo: 'más justa es ella que yo'. Luego volvemos a Egipto (39): José esclavo, próspero, tentado día tras día por la mujer de Potifar, calumniado y encarcelado; y en la cárcel (40), los sueños del copero y del panadero del faraón — interpretados con exactitud, y seguidos por el olvido: 'y el jefe de los coperos no se acordó de José, sino que le olvidó'.",
  c: "El matrimonio por levirato (38:8) —el hermano que da descendencia a la viuda del difunto— era institución conocida en Asiria y entre los hititas, luego regulada en Dt 25; protegía a la viuda y el nombre del muerto en una sociedad donde la mujer sin hijos ni marido quedaba desamparada. El sello cilíndrico con su cordón y el bastón eran la 'firma e identidad' del hombre antiguo: Judá entregó literalmente su identidad a la prostituta del camino. En Egipto, los mayordomos semitas en casas nobles están documentados, igual que la casa-prisión para presos del rey; los títulos ('capitán de la guardia', 'jefe de los coperos y panaderos') corresponden a la corte egipcia real. La interpretación de sueños era ciencia de estado en Egipto, con manuales profesionales; José la desmonta: '¿no son de Dios las interpretaciones?' (40:8).",
  n: "El contraste entre los capítulos 38 y 39 es el punto: Judá, libre, patriarca, busca el pecado y se hunde; José, esclavo, solo, es acosado por el pecado ('hablando ella a José cada día', 39:10) y huye dejando la ropa. Es la segunda vez que una prenda de José miente sobre él —la túnica ensangrentada, el manto en manos de la adúltera— y ambas veces la mentira lo hunde para elevarlo. La frase estructural del capítulo 39 se repite cuatro veces: 'Jehová estaba con José' — en la casa y en la cárcel, en el éxito y en la injusticia. La presencia del pacto no libra de la mazmorra; brilla dentro de ella.",
  p: "¿Por qué interrumpe el narrador con Génesis 38? Porque la línea mesiánica pasa por ahí: de la unión de Judá y Tamar nace Fares, antepasado de David y de Cristo (Rut 4:18-22; Mt 1:3, donde Tamar es una de las cuatro mujeres del árbol genealógico de Jesús). La gracia teje el hilo escarlata con material escandaloso: el Mesías no desciende del impecable José sino del quebrado y confesante Judá. Y la resistencia de José formula la definición eterna de la pureza: 'cómo, pues, haría yo este grande mal, y pecaría contra Dios' (39:9) — el pecado, antes que traición a Potifar, es ofensa contra Dios delante de quien se vive.",
  v: "Thomas Brooks ('Remedios preciosos contra las artimañas de Satanás'): 'huir es la victoria cuando la tentación tiene la puerta cerrada'. Matthew Henry: 'José perdió su capa pero guardó su conciencia'. Spurgeon sobre el copero olvidadizo: 'los hombres olvidan, pero el calendario de Dios no pierde una hoja'.",
  q: "José venció diciendo el pecado por su nombre: 'grande mal contra Dios'. ¿Cómo nombras tú tus tentaciones — con eufemismos que las encogen o con la verdad que las mata?"
 },
 26: {
  t: "Del calabozo al trono: los sueños del faraón",
  h: "Génesis 41–42. Dos años después del olvido del copero, el faraón sueña: siete vacas gordas devoradas por siete flacas, siete espigas llenas tragadas por siete secas. Los magos de Egipto enmudecen, el copero recuerda, y José pasa en una mañana del calabozo al segundo trono del imperio: afeitado a la usanza egipcia, vestido de lino fino, con el anillo real y el collar de oro, a cargo de almacenar el grano de los siete años de abundancia. Llega la hambruna 'en toda la tierra', y con ella, desde Canaán, diez hermanos que se inclinan a tierra ante el gobernador egipcio sin reconocerlo: los sueños de la adolescencia (37:7) se cumplen a veinte años vista.",
  c: "Todo el capítulo 41 respira Egipto auténtico: el Nilo como fuente de vida y de sueños proféticos, las vacas bañándose en el río, la obsesión egipcia con la interpretación onírica y sus 'sabios y magos' profesionales, el afeitado ritual antes de comparecer ante el faraón (los semitas usaban barba; los egipcios no), el anillo con el sello real, el lino fino, el collar de oro como condecoración documentada en tumbas, y el título de visir con autoridad sobre el granero estatal. Los ciclos de hambruna de siete años están registrados en la literatura egipcia. El nuevo nombre (Zafnat-panea) y la esposa de familia sacerdotal de On (Heliópolis) completan la naturalización del esclavo hebreo convertido en estadista.",
  n: "La teología de José estructura la escena: 'no está en mí; Dios será el que dé respuesta propicia al faraón' (41:16), y al faraón pagano le repite el nombre de Dios cuatro veces. Los nombres de sus hijos son su autobiografía espiritual: Manasés ('Dios me hizo olvidar todo mi trabajo') y Efraín ('Dios me hizo fructificar en la tierra de mi aflicción'). En el cap. 42, el espejo moral: los hermanos, presionados por el gobernador que los acusa de espías, confiesan entre ellos —creyendo que nadie los entiende— la culpa enterrada veinte años: 'verdaderamente hemos pecado contra nuestro hermano, pues vimos la angustia de su alma cuando nos rogaba, y no le escuchamos' (42:21). José se aparta y llora. La conciencia dormida despierta cuando la providencia la acorrala.",
  p: "José exaltado tras la humillación es el patrón cristológico por excelencia: 'se humilló a sí mismo... por lo cual Dios también le exaltó hasta lo sumo' (Fil 2:8-9). El esclavo hebreo ante cuyo carro se grita '¡doblad la rodilla!' (41:43) anticipa el Nombre ante el cual se doblará toda rodilla. Y hay más: el único con pan en un mundo hambriento, al que el faraón señala diciendo 'id a José, y haced lo que él os dijere' (41:55), prefigura al que diría 'yo soy el pan de vida'. La prueba dura de los hermanos en el cap. 42 no es venganza sino cirugía: José diseña las circunstancias para resucitar la conciencia y verificar el fruto — como hace la gracia con nosotros.",
  v: "Spurgeon predicó 'Id a José' como sermón evangelístico puro. Matthew Henry sobre Manasés y Efraín: 'Dios puede hacer que su pueblo fructifique en el invierno de la aflicción'. John Flavel: 'la providencia tenía fecha exacta: dos años después, ni un día antes de que el trono estuviera listo'.",
  q: "Dos años más de calabozo después de ayudar al copero. ¿Puedes confiar en el calendario de Dios cuando tu 'copero' te ha olvidado?"
 },
 27: {
  t: "La copa en el costal: Judá ofrece su vida",
  h: "Génesis 43–45. Segunda bajada a Egipto, ahora con Benjamín, arrancado a Jacob con la fianza personal de Judá ('yo te respondo por él', 43:9). José los sienta a su mesa por orden exacto de edad (asombro de los hermanos), colma a Benjamín con porción quíntuple, y luego arma la prueba final: su copa de plata escondida en el costal del menor. Acusados, vueltos a palacio, con Benjamín condenado a esclavitud, llega el momento decisivo: el discurso de Judá (44:18-34), la pieza oratoria más conmovedora del Génesis, que termina ofreciendo su propia vida por el hermano. Entonces José, sin poder contenerse más, despide a los egipcios y llora tan fuerte que lo oye la casa del faraón: 'yo soy José; ¿vive aún mi padre?'.",
  c: "Comer aparte los egipcios de los hebreos (43:32) refleja los tabúes documentados de la sociedad egipcia hacia los pastores extranjeros. La adivinación con copa (hidromancia/lecanomancia: leer los dibujos del aceite en el agua) era práctica egipcia real —José aparenta usarla (44:5,15) como parte de su disfraz, no porque el texto la apruebe. La porción quíntuple al invitado de honor y los asientos por rango pertenecen al protocolo de banquetes oriental. La fianza personal (arrabon) que Judá asume era figura jurídica plena: el fiador respondía con su persona.",
  n: "Toda la prueba de José tiene un solo objetivo: reproducir la escena de hace veinte años —un hijo de Raquel en peligro, la posibilidad de volver a casa libres a costa del hermano— y ver si son los mismos hombres. No lo son. Judá, el que propuso vender a José, ahora dice: 'te ruego que quede tu siervo en lugar del joven por siervo a mi señor, y que el joven vaya con sus hermanos' (44:33). Sustitución voluntaria por amor al padre. Esa es la evidencia del arrepentimiento: no palabras, sino la vieja circunstancia enfrentada con un corazón nuevo. La revelación de José ('yo soy José') funde juicio y perdón en una sola frase de teología: 'no me enviasteis acá vosotros, sino Dios' (45:8).",
  p: "Judá ofreciéndose como sustituto del hermano es el momento en que el futuro portador del cetro (49:10) aprende el oficio de su gran Descendiente: el León de la tribu de Judá que se hará fiador y esclavo en lugar de sus hermanos. Hebreos 7:22 llama a Jesús 'fiador de un mejor pacto' — exactamente lo que Judá hizo con Benjamín, Cristo lo hizo con nosotros ante el Padre: 'ponlo a mi cuenta'. Y Génesis 45:5-8 formula tres veces la doctrina de la providencia sobre el mal: los hermanos vendieron; Dios envió. Ni el mal deja de ser mal, ni deja de servir al plan que salva 'mucha gente' (50:20).",
  v: "Nehemiah Coxe y John Owen sobre la fianza (sponsio) de Cristo en el pacto de redención. Matthew Henry: 'Judá nunca fue tan grande como cuando se ofreció a ser esclavo'. Spurgeon: 'la conversión verdadera se demuestra cuando la vieja tentación encuentra a un hombre nuevo'.",
  q: "La prueba del corazón nuevo es la vieja circunstancia. Si Dios te devolviera hoy a tu antigua tentación, ¿encontraría al mismo hombre?"
 },
 28: {
  t: "Israel baja a Egipto: la promesa emigra sin perderse",
  h: "Génesis 46–47. Jacob, con 130 años, parte hacia Egipto con toda su casa —setenta almas—, pero se detiene en Beerseba, el santuario del sur donde adoraron Abraham e Isaac, y ofrece sacrificios: no quiere repetir el error de bajar a Egipto sin consultar (como Abraham en 12:10). Dios responde en visión nocturna: 'no temas descender a Egipto, porque allí yo haré de ti una gran nación. Yo descenderé contigo... y también te haré volver' (46:3-4). El encuentro de Jacob y José tras veintidós años, el asentamiento en Gosén —la mejor tierra de pastos del delta—, la audiencia ante el faraón donde el anciano pastor bendice al monarca más poderoso de la tierra, y la administración de José durante la hambruna cierran la sección.",
  c: "'Toda abominación es para los egipcios ser pastor de ovejas' (46:34): el desprecio egipcio por los pastores asiáticos está bien documentado, y José lo usa estratégicamente para conseguir Gosén — separados de Egipto, protegidos de la asimilación, juntos como pueblo. La política agraria de José (47:13-26) refleja el sistema egipcio conocido: el faraón como propietario de la tierra, el 20% de impuesto sobre la cosecha, y las tierras de los sacerdotes exentas. La respuesta de Jacob al faraón —'pocos y malos han sido los días de los años de mi vida' (47:9)— es a la vez cortesía oriental y confesión de peregrino: se define como extranjero de paso, como sus padres.",
  n: "La lista de los setenta (46:8-27) es un umbral narrativo: la familia que baja será la nación que suba. El número setenta corresponde a las setenta naciones de Génesis 10 — Israel en embrión es una humanidad en miniatura, el pueblo por el cual serán benditas todas las familias de la tierra. El abrazo de Jacob y José ('muera yo ahora, ya que he visto tu rostro', 46:30) es el Nunc dimittis del Génesis, eco anticipado de Simeón. Y el detalle final del cap. 47: Jacob hace jurar a José que no lo enterrará en Egipto sino con sus padres — el anciano que emigró de cuerpo jamás emigró de fe: su tumba debe predicar la promesa.",
  p: "Hebreos 11:13-16 lee estas escenas: confesaron que eran 'extranjeros y peregrinos sobre la tierra', buscando la patria mejor. La bajada a Egipto es parte del plan anunciado a Abraham (15:13-16): cuatrocientos años, esclavitud y regreso. Dios instala a su pueblo en la incubadora de Gosén, donde crecerá de familia a nación sin disolverse entre los cananeos. La promesa 'yo descenderé contigo... y te haré volver' (46:4) es el evangelio en itinerario: Emanuel desciende con su pueblo a toda esclavitud y garantiza el éxodo. Ningún Egipto de tu vida está fuera del mapa del pacto.",
  v: "Matthew Henry: 'la presencia de Dios en el descenso hace seguro cualquier descenso'. Thomas Watson sobre el peregrinaje: 'el santo tiene el mundo por posada, no por hogar'. Calvino subraya que Jacob bendijo al faraón: 'el menor es bendecido por el mayor... la dignidad espiritual sobrepasa la corona'.",
  q: "Jacob se presentó ante el faraón como peregrino y ante la muerte como heredero. ¿Cuál de las dos identidades gobierna tus decisiones: residente de Egipto o heredero de la promesa?"
 },
 29: {
  t: "Las bendiciones de Jacob: el cetro de Judá",
  h: "Génesis 48–50. Jacob moribundo adopta y bendice a los dos hijos de José —cruzando las manos para poner a Efraín, el menor, sobre Manasés: última inversión de primogenituras del Génesis— y luego convoca a los doce para el gran oráculo profético del cap. 49: el futuro de cada tribu, con las cumbres de Judá (el cetro y Siloh) y José (el vástago fructífero). Muere a los 147 años; Egipto lo llora setenta días; un cortejo de estado lo lleva a Macpela. El libro cierra con la escena definitiva: los hermanos temen la venganza, y José pronuncia el credo de toda la historia ('vosotros pensasteis mal contra mí, mas Dios lo encaminó a bien'), muere a los 110 años —la edad ideal egipcia— y deja mandado que sus huesos suban con el éxodo. Génesis termina con 'un ataúd en Egipto'... cargado de promesa.",
  c: "La adopción de los nietos sobre las rodillas (48:12) y la bendición con imposición de manos son gestos jurídicos de legitimación conocidos en el antiguo Oriente; al adoptar a Efraín y Manasés, Jacob da a José la doble porción del primogénito (48:22; 1Cr 5:1-2). El oráculo tribal en poesía arcaica (49) pertenece al género de 'bendiciones del lecho de muerte' con valor testamentario vinculante. El embalsamamiento de cuarenta días, los setenta días de duelo nacional y el ataúd (sarcófago) son ritos funerarios egipcios exactos —aplicados a un patriarca que será enterrado en una cueva de Canaán: síntesis perfecta de sus dos mundos.",
  n: "Las manos cruzadas de Jacob ciego (48:14) son la firma del Génesis entero: Dios elige contra el orden natural —Abel no Caín, Isaac no Ismael, Jacob no Esaú, Efraín no Manasés— para que nadie se gloríe. La confesión de Jacob al bendecir es la primera mención del 'Ángel que me liberta de todo mal' (48:16) como redentor (goel) personal. En el cap. 50, el círculo moral se cierra: los hermanos, aún sin poder creer el perdón, inventan un mensaje del padre muerto; José llora —otra vez— y responde con la pregunta que desarma toda venganza: '¿acaso estoy yo en lugar de Dios?' (50:19). El perdonado de verdad renuncia al tribunal.",
  p: "Génesis 49:10 es la profecía mesiánica capital del libro: 'no será quitado el cetro de Judá... hasta que venga Siloh, y a él se congregarán los pueblos'. La realeza queda anclada en Judá mil años antes de David, y su meta final —la congregación de los pueblos— solo se cumple en Cristo (cf. Ap 5:5, 'el León de la tribu de Judá'). Y Génesis 50:20 junto a 50:24-25 dejan el testamento doctrinal del libro: providencia soberana sobre el mal ('Dios lo encaminó a bien para hacer vivir a mucho pueblo') y esperanza pactual contra toda apariencia ('Dios ciertamente os visitará': los huesos de José esperaron el éxodo 400 años, y Moisés los cargó, Éx 13:19). La fe del Génesis muere sin recibir lo prometido, pero saludándolo de lejos.",
  v: "Matthew Henry sobre 49:10: 'el cetro esperó a Siloh, y cuando Siloh vino, el cetro pasó a manos eternas'. John Gill defiende la lectura mesiánica de Siloh con toda la tradición judía antigua. Spurgeon sobre 50:20: 'la soberanía de Dios es la almohada donde el creyente reposa su cabeza'.",
  q: "José no vio el éxodo, pero dio órdenes sobre sus huesos. ¿Qué decisiones tuyas de hoy predican que crees en promesas que no verás cumplidas en vida?"
 },
 30: {
  t: "Éxodo: el Dios que oye, recuerda, ve y conoce",
  h: "Éxodo 1–3. Han pasado unos cuatro siglos desde José. Israel se ha multiplicado hasta llenar Gosén, y 'se levantó un nuevo rey que no conocía a José': el clima político cambió (posiblemente tras la expulsión de los hicsos, gobernantes semitas, que volvió sospechoso todo lo asiático). Vienen las medidas de opresión escalonada: trabajos forzados en Pitón y Ramesés (ciudades-almacén del delta, arqueológicamente identificables), luego el infanticidio por las parteras, luego el decreto público: todo niño hebreo al Nilo. En ese contexto nace Moisés, salvado por tres mujeres y una canasta, criado en la corte, fugitivo en Madián a los cuarenta, y llamado a los ochenta desde la zarza que arde sin consumirse.",
  c: "La ironía histórica es exquisita: el faraón teme la fecundidad hebrea y ordena usar el Nilo como arma; Dios usa el Nilo, una cesta calafateada (tebah, la misma palabra que 'arca' de Noé) y a la propia hija del faraón para criar al libertador en el palacio del opresor —con sueldo pagado a la madre biológica. Las parteras Sifra y Fúa, dos mujeres con nombre frente a un faraón sin nombre, protagonizan el primer caso registrado de desobediencia civil por temor de Dios (1:17). La zarza (seneh) arde en el 'monte de Dios, Horeb': el fuego divino habita lo humilde sin destruirlo — emblema de la zarza-Israel en el horno de Egipto, y de toda morada de Dios con el hombre.",
  n: "Éxodo 2:23-25 es el gozne teológico con cuatro verbos: Dios oyó el gemido, se acordó de su pacto con Abraham, miró a los hijos de Israel, y los conoció. El silencio de cuatro siglos no fue olvido: era calendario (Gn 15:13-16). En la zarza, Dios se presenta primero por historia ('el Dios de Abraham, Isaac y Jacob') y luego por esencia: 'YO SOY EL QUE SOY' (3:14) — el Nombre (YHWH) que declara aseidad, eternidad, fidelidad incondicionada: el Dios que es, sin causa ni dependencia, y que por eso puede prometer sin riesgo de fallar. Las cinco objeciones de Moisés (3:11–4:17) reciben una sola respuesta de fondo: 'ciertamente yo estaré contigo'. La suficiencia del siervo es la presencia del que envía.",
  p: "El éxodo será el paradigma de redención de toda la Biblia, y arranca aquí como acto de memoria pactual: Dios baja a librar 'porque se acordó de su pacto'. Jesús usará la zarza para probar la resurrección ('el Dios de Abraham... no es Dios de muertos, sino de vivos', Mr 12:26-27) y tomará el Nombre para sí en los 'YO SOY' de Juan — 'antes que Abraham fuese, yo soy' (Jn 8:58). El libertador antes rechazado ('¿quién te ha puesto a ti por príncipe y juez?', 2:14) que vuelve como redentor es patrón de Cristo (Hch 7:35). La redención no comienza cuando el pueblo se organiza sino cuando Dios desciende.",
  v: "La Confesión de 1689, cap. 2, sobre el Nombre: Dios 'es todo suficiente en sí y para sí, no necesitando ninguna criatura'. Stephen Charnock sobre la aseidad divina. Matthew Henry: 'la zarza ardía y no se consumía: la iglesia perseguida nunca es consumida, porque Dios está en medio de ella'.",
  q: "Dios se presentó como 'YO SOY', no como 'yo fui' ni 'yo seré solamente'. ¿Vives tu prueba actual con un Dios presente, o lo tienes archivado en el pasado y aplazado al futuro?"
 },
 31: {
  t: "«Deja ir a mi pueblo»: la vara, las excusas y el Redentor",
  h: "Éxodo 4–6. Moisés agota sus objeciones —'no me creerán', 'soy tardo en el habla', y la definitiva: 'envía a otro' (4:13)— y Dios, airado pero paciente, le da señales (la vara-serpiente, la mano leprosa) y a Aarón como boca. El regreso a Egipto incluye el episodio enigmático de la circuncisión omitida (4:24-26): el mediador del pacto no puede marchar con el pacto descuidado en su propia casa. La primera audiencia ante el faraón es un desastre calculado: 'ni yo dejaré ir a Israel' —y el castigo: ladrillos sin paja. El pueblo, más oprimido que antes, maldice a sus libertadores; Moisés se queja a Dios; y Dios responde con la declaración pactual más densa del libro (6:2-8).",
  c: "'¿Quién es Jehová para que yo oiga su voz?' (5:2): en la teología política egipcia, el faraón era hijo de Ra y encarnación de Horus; la pregunta es sincera —ningún dios extranjero de esclavos figuraba en su panteón. Las pilas de ladrillos de adobe con y sin paja subsisten en Egipto; los registros egipcios documentan cuotas diarias de ladrillos y capataces con listas —el retrato laboral de Éx 5 es fotográfico. La demanda inicial ('tres días de camino para sacrificar en el desierto') sigue el protocolo negociador oriental: una petición mínima cuya negativa desnuda la tiranía del que la niega.",
  n: "Éxodo 6:2-8 está construido sobre siete 'yo' divinos: yo soy Jehová, aparecí, establecí mi pacto, he oído el gemido, me he acordado, os sacaré-libraré-redimiré, os tomaré por mi pueblo. El verbo central es ga'al, redimir: el término del pariente-rescatador (el goel de Job y Rut) aplicado por primera vez a Dios como Redentor nacional: 'os redimiré con brazo extendido' (6:6). Nota el realismo del texto: ante este evangelio, el pueblo 'no escuchaba a Moisés a causa de la congoja de espíritu y de la dura servidumbre' (6:9). Hay opresiones tan largas que ya no dejan oír las promesas — y Dios redime igual, no porque le oigan bien, sino porque juró.",
  p: "Aquí se forja el vocabulario de la salvación que el Nuevo Testamento heredará entero: redención (apolytrosis), sangre, primogénito, pascua, pueblo adquirido. 'Os tomaré por mi pueblo y seré vuestro Dios' (6:7) es la fórmula del pacto que atraviesa la Escritura hasta cerrarla: 'he aquí el tabernáculo de Dios con los hombres... ellos serán su pueblo, y Dios mismo estará con ellos' (Ap 21:3). El empeoramiento antes de la liberación (ladrillos sin paja) es pedagogía habitual de la redención: Dios deja que la esclavitud muestre todo su rostro para que la salvación no comparta la gloria con nadie. Y las excusas de Moisés consuelan a todo siervo: Dios no llama capacitados; capacita llamados, y la boca del tartamudo pronunciará el juicio de Egipto.",
  v: "Nehemiah Coxe sobre la fórmula 'seré vuestro Dios' como sustancia de todos los pactos. Matthew Henry: 'la hora más oscura de Israel fue la víspera de su redención'. John Owen: la redención es obra del Dios trino que se acuerda de su pacto aun cuando su pueblo ya no puede ni escucharlo.",
  q: "Israel no podía oír las promesas 'a causa de la congoja'. Cuando tú no sientes nada al leer la Palabra, ¿depende la fidelidad de Dios de la calidad de tu escucha?"
 }
};
