/* Confesiones de fe — textos históricos de dominio público, versión en español */
const CONFESIONES = {
lbc: {
titulo: 'Confesión de Fe Bautista de Londres (1689)',
nota: 'Confesión de Fe Bautista de Londres de 1689. Texto histórico de dominio público. Las referencias bíblicas entre paréntesis son las pruebas señaladas por los autores.',
caps: [
{ t: 'De las Santas Escrituras', p: [
'La Santa Escritura es la única regla suficiente, segura e infalible de todo conocimiento salvador, fe y obediencia. Aunque la luz de la naturaleza y las obras de la creación y de la providencia manifiestan de tal manera la bondad, sabiduría y poder de Dios que dejan a los hombres sin excusa, no son suficientes para dar aquel conocimiento de Dios y de su voluntad que es necesario para la salvación. Por tanto, agradó al Señor, en distintas épocas y de diversas maneras, revelarse a sí mismo y declarar su voluntad a su iglesia; y después, para preservar y propagar mejor la verdad, y para el más seguro establecimiento y consuelo de la iglesia contra la corrupción de la carne y la malicia de Satanás y del mundo, le agradó poner por escrito esa revelación en su totalidad, lo cual hace a las Santas Escrituras absolutamente necesarias, habiendo cesado ya aquellas maneras anteriores por las cuales Dios revelaba su voluntad a su pueblo. (2 Ti 3:15-17; Is 8:20; Lc 16:29,31; Ef 2:20; Ro 1:19-21; Ro 2:14-15; Sal 19:1-3; He 1:1; Pr 22:19-21; Ro 15:4; 2 P 1:19-20)',
'Bajo el nombre de Santa Escritura, o Palabra de Dios escrita, se contienen ahora todos los libros del Antiguo y Nuevo Testamento, que son: Génesis, Éxodo, Levítico, Números, Deuteronomio, Josué, Jueces, Rut, 1 Samuel, 2 Samuel, 1 Reyes, 2 Reyes, 1 Crónicas, 2 Crónicas, Esdras, Nehemías, Ester, Job, Salmos, Proverbios, Eclesiastés, Cantar de los Cantares, Isaías, Jeremías, Lamentaciones, Ezequiel, Daniel, Oseas, Joel, Amós, Abdías, Jonás, Miqueas, Nahúm, Habacuc, Sofonías, Hageo, Zacarías, Malaquías, Mateo, Marcos, Lucas, Juan, Hechos, Romanos, 1 Corintios, 2 Corintios, Gálatas, Efesios, Filipenses, Colosenses, 1 Tesalonicenses, 2 Tesalonicenses, 1 Timoteo, 2 Timoteo, Tito, Filemón, Hebreos, Santiago, 1 Pedro, 2 Pedro, 1 Juan, 2 Juan, 3 Juan, Judas y Apocalipsis. Todos ellos son dados por inspiración de Dios para ser la regla de fe y de vida. (2 Ti 3:16)',
'Los libros comúnmente llamados Apócrifos, no siendo de inspiración divina, no forman parte del canon o regla de la Escritura y, por tanto, no tienen autoridad para la iglesia de Dios, ni deben ser aprobados o usados de otra manera que otros escritos humanos. (Lc 24:27,44; Ro 3:2)',
'La autoridad de la Santa Escritura, por la cual debe ser creída, no depende del testimonio de ningún hombre o iglesia, sino enteramente de Dios (quien es la verdad misma), su autor; por lo tanto, debe ser recibida porque es la Palabra de Dios. (2 P 1:19-21; 2 Ti 3:16; 1 Ts 2:13; 1 Jn 5:9)',
'Podemos ser movidos e inducidos por el testimonio de la iglesia de Dios a una estima alta y reverente de las Santas Escrituras; y el carácter celestial de su contenido, la eficacia de su doctrina, la majestad de su estilo, la armonía de todas sus partes, el fin que persigue en su totalidad (que es dar toda la gloria a Dios), la plena revelación que hace del único camino de salvación del hombre, y muchas otras excelencias incomparables y plena perfección de la misma, son argumentos por los cuales da abundante evidencia de ser la Palabra de Dios. Sin embargo, nuestra plena persuasión y certeza de su verdad infalible y autoridad divina proviene de la obra interna del Espíritu Santo, que da testimonio por medio de la Palabra y con la Palabra en nuestros corazones. (Jn 16:13-14; 1 Co 2:10-12; 1 Jn 2:20,27)',
'Todo el consejo de Dios tocante a todas las cosas necesarias para su propia gloria, la salvación del hombre, la fe y la vida, está expresamente declarado o necesariamente contenido en la Santa Escritura; a la cual nada, en ningún tiempo, ha de añadirse, ni por nueva revelación del Espíritu ni por las tradiciones de los hombres. Sin embargo, reconocemos que la iluminación interna del Espíritu de Dios es necesaria para el entendimiento salvador de las cosas reveladas en la Palabra, y que hay algunas circunstancias tocantes a la adoración de Dios y al gobierno de la iglesia, comunes a las acciones y sociedades humanas, que han de ordenarse conforme a la luz de la naturaleza y de la prudencia cristiana, según las reglas generales de la Palabra, que siempre deben observarse. (2 Ti 3:15-17; Gá 1:8-9; Jn 6:45; 1 Co 2:9-12; 1 Co 11:13-14; 1 Co 14:26,40)',
'No todas las cosas contenidas en la Escritura son igualmente claras en sí mismas, ni igualmente claras para todos; sin embargo, las cosas que necesariamente deben saberse, creerse y observarse para la salvación se proponen y explican tan claramente en uno u otro lugar de la Escritura, que no solo los eruditos, sino también los que no lo son, pueden alcanzar un entendimiento suficiente de ellas mediante el debido uso de los medios ordinarios. (2 P 3:16; Sal 19:7; Sal 119:130)',
'El Antiguo Testamento en hebreo (que era la lengua nativa del pueblo de Dios en la antigüedad) y el Nuevo Testamento en griego (que en el tiempo en que fue escrito era la lengua más generalmente conocida entre las naciones), siendo inspirados inmediatamente por Dios y mantenidos puros a lo largo de los siglos por su cuidado y providencia singulares, son por tanto auténticos; de modo que en toda controversia religiosa la iglesia debe apelar a ellos como autoridad final. Pero como estas lenguas originales no son conocidas por todo el pueblo de Dios, que tiene derecho a las Escrituras e interés en ellas, y a quien se le manda leerlas y escudriñarlas en el temor de Dios, deben traducirse a la lengua común de toda nación a la que lleguen, para que, morando abundantemente la Palabra de Dios en todos, puedan adorarle de manera aceptable y, por la paciencia y consolación de las Escrituras, tengan esperanza. (Ro 3:2; Is 8:20; Hch 15:15; Jn 5:39; 1 Co 14:6,9,11-12,24,28; Col 3:16)',
'La regla infalible de interpretación de la Escritura es la Escritura misma; y, por consiguiente, cuando surge una duda respecto al sentido verdadero y pleno de cualquier pasaje (que no es múltiple, sino uno), este debe buscarse mediante otros pasajes que hablen con más claridad. (2 P 1:20-21; Hch 15:15-16)',
'El juez supremo, por el cual deben decidirse todas las controversias religiosas y examinarse todos los decretos de concilios, las opiniones de los escritores antiguos, las doctrinas de hombres y los espíritus privados, y en cuya sentencia hemos de descansar, no puede ser otro que la Santa Escritura entregada por el Espíritu. A dicha Escritura así entregada se reduce nuestra fe en última instancia. (Mt 22:29,31-32; Ef 2:20; Hch 28:23)'
]},
{ t: 'De Dios y de la Santa Trinidad', p: [
'El Señor nuestro Dios es un solo Dios vivo y verdadero; cuya subsistencia está en sí mismo y es de sí mismo, infinito en ser y perfección; cuya esencia no puede ser comprendida por nadie sino por él mismo; espíritu purísimo, invisible, sin cuerpo, miembros ni pasiones; el único que tiene inmortalidad, que habita en luz inaccesible; inmutable, inmenso, eterno, incomprensible, todopoderoso, infinito en todo sentido, santísimo, sapientísimo, libérrimo, absolutísimo; que hace todas las cosas según el consejo de su propia voluntad inmutable y justísima, para su propia gloria; amantísimo, benigno, misericordioso, longánimo, abundante en bondad y verdad, que perdona la iniquidad, la transgresión y el pecado; galardonador de los que le buscan con diligencia; y, con todo, justísimo y terrible en sus juicios, que odia todo pecado y de ninguna manera dará por inocente al culpable. (1 Co 8:4,6; Dt 6:4; Jer 10:10; Is 48:12; Éx 3:14; Jn 4:24; 1 Ti 1:17; Dt 4:15-16; Mal 3:6; 1 R 8:27; Jer 23:23; Sal 90:2; Gn 17:1; Is 6:3; Sal 115:3; Is 46:10; Pr 16:4; Ro 11:36; Éx 34:6-7; He 11:6; Neh 9:32-33; Sal 5:5-6; Éx 34:7; Nah 1:2-3)',
'Dios, teniendo toda vida, gloria, bondad y bienaventuranza en sí mismo y de sí mismo, es el único autosuficiente, y no necesita de ninguna criatura que él haya hecho, ni deriva gloria alguna de ellas, sino que solamente manifiesta su propia gloria en ellas, por ellas, hacia ellas y sobre ellas. Él es la sola fuente de todo ser, de quien, por quien y para quien son todas las cosas; y tiene sobre todas las criaturas dominio soberanísimo para hacer por medio de ellas, para ellas o sobre ellas todo lo que le plazca. Ante su vista todas las cosas están abiertas y manifiestas; su conocimiento es infinito, infalible e independiente de la criatura, de modo que para él nada es contingente o incierto. Es santísimo en todos sus consejos, en todas sus obras y en todos sus mandatos. A él se le debe, de parte de los ángeles y de los hombres, todo culto, servicio u obediencia que como criaturas deben al Creador, y todo lo demás que él tenga a bien requerir de ellos. (Jn 5:26; Sal 148:13; Sal 119:68; Job 22:2-3; Ro 11:34-36; Dn 4:25,34-35; He 4:13; Ez 11:5; Hch 15:18; Sal 145:17; Ap 5:12-14)',
'En este Ser divino e infinito hay tres subsistencias: el Padre, el Verbo o Hijo, y el Espíritu Santo; de una misma sustancia, poder y eternidad, teniendo cada uno toda la esencia divina, sin que esta sea dividida: el Padre no es de nadie, ni por generación ni por procesión; el Hijo es eternamente engendrado del Padre; el Espíritu Santo procede del Padre y del Hijo. Todos ellos son infinitos, sin principio, y por tanto un solo Dios, que no debe ser dividido en naturaleza y ser, sino distinguido por varias propiedades relativas peculiares y relaciones personales. Esta doctrina de la Trinidad es el fundamento de toda nuestra comunión con Dios y de nuestra consoladora dependencia de él. (1 Jn 5:7; Mt 28:19; 2 Co 13:14; Éx 3:14; Jn 14:11; 1 Co 8:6; Jn 1:14,18; Jn 15:26; Gá 4:6)'
]},
{ t: 'Del decreto de Dios', p: [
'Dios ha decretado en sí mismo, desde toda la eternidad, por el sapientísimo y santísimo consejo de su propia voluntad, libre e inmutablemente, todas las cosas que suceden; sin embargo, de tal manera que Dios ni es autor del pecado ni tiene comunión con nadie en él; ni se hace violencia a la voluntad de la criatura, ni es quitada la libertad o contingencia de las causas segundas, sino más bien establecida; en lo cual se manifiesta su sabiduría en disponer todas las cosas, y su poder y fidelidad en cumplir su decreto. (Is 46:10; Ef 1:11; He 6:17; Ro 9:15,18; Stg 1:13; 1 Jn 1:5; Hch 4:27-28; Jn 19:11; Nm 23:19; Ef 1:3-5)',
'Aunque Dios conoce todo lo que puede o podría suceder bajo todas las condiciones supuestas, nada ha decretado porque lo previera como futuro o como cosa que sucedería en tales condiciones. (Hch 15:18; Ro 9:11,13,16,18)',
'Por el decreto de Dios, para la manifestación de su gloria, algunos hombres y ángeles son predestinados, o preordinados, a vida eterna por medio de Jesucristo, para alabanza de su gloriosa gracia; otros son dejados para que actúen en su pecado para su justa condenación, para alabanza de su gloriosa justicia. (1 Ti 5:21; Mt 25:34; Ef 1:5-6; Ro 9:22-23; Jud 4)',
'Estos ángeles y hombres así predestinados y preordinados están particular e inmutablemente designados, y su número es tan cierto y definido que no puede ser aumentado ni disminuido. (2 Ti 2:19; Jn 13:18)',
'A aquellos de la humanidad que están predestinados a la vida, Dios, antes de la fundación del mundo, conforme a su propósito eterno e inmutable y al consejo secreto y beneplácito de su voluntad, los ha escogido en Cristo para gloria eterna, por su mera gracia y amor, sin ninguna otra cosa en la criatura como condición o causa que le moviera a ello. (Ef 1:4,9,11; Ro 8:30; 2 Ti 1:9; 1 Ts 5:9; Ro 9:13,16; Ef 2:5,12)',
'Como Dios ha designado a los elegidos para la gloria, así también, por el propósito eterno y libérrimo de su voluntad, ha preordinado todos los medios para ello; por lo cual los que son elegidos, habiendo caído en Adán, son redimidos por Cristo, son eficazmente llamados a la fe en Cristo por su Espíritu que obra en el tiempo debido, son justificados, adoptados, santificados y guardados por su poder mediante la fe para salvación. Ningún otro es redimido por Cristo, ni eficazmente llamado, justificado, adoptado, santificado y salvado, sino solamente los elegidos. (1 P 1:2; 2 Ts 2:13; 1 Ts 5:9-10; Ro 8:30; 2 Ts 2:13; 1 P 1:5; Jn 10:26; Jn 17:9; Jn 6:64)',
'La doctrina de este alto misterio de la predestinación debe tratarse con especial prudencia y cuidado, para que los hombres, atendiendo a la voluntad de Dios revelada en su Palabra y obedeciéndola, puedan, por la certeza de su llamamiento eficaz, estar seguros de su elección eterna; de manera que esta doctrina proporcione motivo de alabanza, reverencia y admiración de Dios, y de humildad, diligencia y abundante consuelo a todos los que sinceramente obedecen el evangelio. (1 Ts 1:4-5; 2 P 1:10; Ef 1:6; Ro 11:33; Ro 11:5-6,20; Lc 10:20)'
]},
{ t: 'De la creación', p: [
'En el principio agradó a Dios Padre, Hijo y Espíritu Santo, para la manifestación de la gloria de su poder, sabiduría y bondad eternos, crear o hacer el mundo y todas las cosas que en él hay, tanto visibles como invisibles, en el espacio de seis días, y todo muy bueno. (Jn 1:2-3; He 1:2; Job 26:13; Ro 1:20; Col 1:16; Gn 1:31)',
'Después que Dios hubo hecho todas las demás criaturas, creó al hombre, varón y hembra, con almas racionales e inmortales, haciéndolos aptos para aquella vida para con Dios para la cual fueron creados; siendo hechos a imagen de Dios, en conocimiento, justicia y santidad verdadera, teniendo la ley de Dios escrita en sus corazones y el poder para cumplirla; y, sin embargo, con la posibilidad de transgredirla, al ser dejados a la libertad de su propia voluntad, que era mutable. (Gn 1:27; Gn 2:7; Ec 7:29; Gn 1:26; Ro 2:14-15; Gn 3:6)',
'Además de la ley escrita en sus corazones, recibieron el mandato de no comer del árbol del conocimiento del bien y del mal; y mientras lo guardaron, fueron felices en su comunión con Dios y tuvieron dominio sobre las criaturas. (Gn 2:17; Gn 1:26,28)'
]},
{ t: 'De la divina providencia', p: [
'Dios, el buen Creador de todas las cosas, en su infinito poder y sabiduría sostiene, dirige, dispone y gobierna a todas las criaturas y cosas, desde la más grande hasta la más pequeña, por su sapientísima y santísima providencia, para el fin para el cual fueron creadas, según su presciencia infalible y el libre e inmutable consejo de su propia voluntad; para alabanza de la gloria de su sabiduría, poder, justicia, infinita bondad y misericordia. (He 1:3; Job 38:11; Is 46:10-11; Sal 135:6; Mt 10:29-31; Ef 1:11)',
'Aunque en relación con la presciencia y el decreto de Dios, la causa primera, todas las cosas suceden inmutable e infaliblemente, de modo que nada acontece a nadie por azar o fuera de su providencia; sin embargo, por la misma providencia, Dios las ordena de tal manera que ocurran conforme a la naturaleza de las causas segundas, sea necesaria, libre o contingentemente. (Hch 2:23; Pr 16:33; Gn 8:22)',
'Dios, en su providencia ordinaria, hace uso de medios; sin embargo, es libre para obrar sin ellos, sobre ellos y contra ellos, según le plazca. (Hch 27:31,44; Is 55:10-11; Os 1:7; Ro 4:19-21; Dn 3:27)',
'El poder omnipotente, la sabiduría inescrutable y la bondad infinita de Dios se manifiestan en su providencia de tal manera que su consejo determinado se extiende aun hasta la primera caída y a todas las demás acciones pecaminosas, tanto de ángeles como de hombres (y esto no por un mero permiso), las cuales sapientísima y poderosamente limita, y asimismo ordena y gobierna de múltiples maneras para sus santísimos fines; pero de tal modo que la pecaminosidad de dichas acciones procede solamente de las criaturas y no de Dios, quien, siendo santísimo y justísimo, ni es ni puede ser autor o aprobador del pecado. (Ro 11:32-34; 2 S 24:1 con 1 Cr 21:1; 2 R 19:28; Sal 76:10; Gn 50:20; Is 10:6-7,12; Sal 50:21; 1 Jn 2:16)',
'El sapientísimo, justísimo y clementísimo Dios muchas veces deja por algún tiempo a sus propios hijos en múltiples tentaciones y en la corrupción de sus propios corazones, para castigarlos por sus pecados anteriores o para descubrirles la fuerza oculta de la corrupción y el engaño de sus corazones, a fin de que sean humillados; y para llevarlos a una dependencia de él más íntima y constante para su sostén, y para hacerlos más vigilantes contra todas las ocasiones futuras de pecado, y para otros muchos fines santos y justos. De modo que todo lo que acontece a cualquiera de sus elegidos es por su designio, para su gloria y el bien de ellos. (2 Cr 32:25-26,31; 2 Co 12:7-9; Ro 8:28)',
'En cuanto a aquellos hombres malvados e impíos a quienes Dios, como juez justo, ciega y endurece a causa de sus pecados anteriores, no solo les niega su gracia, por la cual podrían haber sido iluminados en su entendimiento y movidos en sus corazones, sino que también a veces retira los dones que tenían, y los deja expuestos a aquellas cosas que su corrupción convierte en ocasión de pecado; y además los entrega a sus propias concupiscencias, a las tentaciones del mundo y al poder de Satanás, por lo cual sucede que se endurecen a sí mismos bajo los mismos medios que Dios emplea para ablandar a otros. (Ro 1:24-26,28; Ro 11:7-8; Dt 29:4; Mt 13:12; Dt 2:30; 2 R 8:12-13; Sal 81:11-12; 2 Ts 2:10-12; Éx 8:15,32; Is 6:9-10; 1 P 2:7-8)',
'Como la providencia de Dios alcanza en general a todas las criaturas, así de una manera muy especial cuida de su iglesia y dispone todas las cosas para el bien de ella. (1 Ti 4:10; Am 9:8-9; Is 43:3-5)'
]},
{ t: 'De la caída del hombre, del pecado y su castigo', p: [
'Aunque Dios creó al hombre recto y perfecto, y le dio una ley justa que hubiera sido para vida si la hubiera guardado, amenazándole con la muerte si la quebrantaba, el hombre no permaneció mucho tiempo en este honor: Satanás, usando la sutileza de la serpiente para subyugar a Eva, sedujo luego por medio de ella a Adán, quien, sin ninguna coacción, transgredió voluntariamente la ley de su creación y el mandato que se le había dado, comiendo del fruto prohibido; lo cual agradó a Dios permitir, conforme a su sabio y santo consejo, habiendo propuesto ordenarlo para su propia gloria. (Gn 2:16-17; Gn 3:12-13; 2 Co 11:3)',
'Nuestros primeros padres, por este pecado, cayeron de su justicia original y de la comunión con Dios, y nosotros caímos en ellos, por lo cual la muerte pasó a todos los hombres: todos vinieron a ser muertos en pecado y totalmente corrompidos en todas las facultades y partes del alma y del cuerpo. (Ro 3:23; Ro 5:12; Tit 1:15; Gn 6:5; Jer 17:9; Ro 3:10-19)',
'Siendo ellos la raíz de toda la humanidad, y estando por designio de Dios en lugar de todo el género humano, la culpa del pecado fue imputada y la naturaleza corrompida transmitida a toda su posteridad descendiente de ellos por generación ordinaria, siendo todos concebidos en pecado y por naturaleza hijos de ira, siervos del pecado, sujetos a la muerte y a todas las demás miserias espirituales, temporales y eternas, a menos que el Señor Jesús los ponga en libertad. (Ro 5:12-19; 1 Co 15:21-22; Sal 51:5; Job 14:4; Ef 2:3; Ro 6:20; He 2:14-15; 1 Ts 1:10)',
'De esta corrupción original, por la cual estamos completamente indispuestos, incapacitados y opuestos a todo bien, y enteramente inclinados a todo mal, proceden todas las transgresiones actuales. (Ro 8:7; Col 1:21; Stg 1:14-15; Mt 15:19)',
'Esta corrupción de naturaleza permanece durante esta vida en los que son regenerados; y aunque sea perdonada y mortificada por medio de Cristo, tanto ella misma como sus primeros impulsos son verdadera y propiamente pecado. (Ro 7:18,23; Ec 7:20; 1 Jn 1:8; Ro 7:23-25; Gá 5:17)'
]},
{ t: 'Del pacto de Dios', p: [
'La distancia entre Dios y la criatura es tan grande que, aunque las criaturas racionales le deben obediencia como a su Creador, jamás hubieran podido alcanzar la recompensa de la vida sino por alguna condescendencia voluntaria de parte de Dios, que a él le ha placido expresar por vía de pacto. (Lc 17:10; Job 35:7-8)',
'Además, habiéndose el hombre acarreado la maldición de la ley por su caída, agradó al Señor hacer un pacto de gracia, en el cual ofrece gratuitamente a los pecadores vida y salvación por Jesucristo, requiriéndoles fe en él para que sean salvos, y prometiendo dar su Espíritu Santo a todos aquellos que están ordenados para vida eterna, a fin de hacerlos dispuestos y capaces de creer. (Gn 2:17; Gá 3:10; Ro 3:20-21; Ro 8:3; Mr 16:15-16; Jn 3:16; Ez 36:26-27; Jn 6:44-45; Sal 110:3)',
'Este pacto se revela en el evangelio; primeramente a Adán en la promesa de salvación por la simiente de la mujer, y después, por pasos sucesivos, hasta completarse su plena revelación en el Nuevo Testamento; y se funda en aquella transacción federal y eterna que hubo entre el Padre y el Hijo acerca de la redención de los elegidos; y es solamente por la gracia de este pacto que todos los descendientes del Adán caído que han sido salvos obtuvieron vida y bendita inmortalidad, no siendo el hombre ya capaz en absoluto de ser aceptado por Dios bajo aquellas condiciones en que estuvo Adán en su estado de inocencia. (Gn 3:15; He 1:1; 2 Ti 1:9; Tit 1:2; He 11:6,13; Ro 4:1-2; Hch 4:12; Jn 8:56)'
]},
{ t: 'De Cristo el Mediador', p: [
'Agradó a Dios, en su propósito eterno, escoger y ordenar al Señor Jesús, su Hijo unigénito, conforme al pacto hecho entre ambos, para que fuera el mediador entre Dios y el hombre; profeta, sacerdote y rey; cabeza y salvador de la iglesia, heredero de todas las cosas y juez del mundo; a quien dio desde toda la eternidad un pueblo para que fuera su simiente, y para que en el tiempo debido lo redimiera, llamara, justificara, santificara y glorificara. (Is 42:1; 1 P 1:19-20; Hch 3:22; He 5:5-6; Sal 2:6; Lc 1:33; Ef 1:22-23; He 1:2; Hch 17:31; Is 53:10; Jn 17:6; Ro 8:30)',
'El Hijo de Dios, la segunda persona de la Santa Trinidad, siendo verdadero y eterno Dios, resplandor de la gloria del Padre, de una misma sustancia con aquel e igual a él, quien hizo el mundo y quien sostiene y gobierna todas las cosas que ha hecho, cuando llegó la plenitud del tiempo tomó sobre sí la naturaleza del hombre, con todas sus propiedades esenciales y sus debilidades comunes, aunque sin pecado; siendo concebido por el Espíritu Santo en el vientre de la virgen María, al venir sobre ella el Espíritu Santo y cubrirla con su sombra el poder del Altísimo; y así fue hecho de una mujer de la tribu de Judá, de la simiente de Abraham y de David según las Escrituras; de manera que dos naturalezas completas, perfectas y distintas se unieron inseparablemente en una sola persona, sin conversión, composición ni confusión alguna; cuya persona es verdadero Dios y verdadero hombre, aunque un solo Cristo, el único mediador entre Dios y el hombre. (Jn 1:14; Gá 4:4; Ro 8:3; He 2:14,16-17; He 4:15; Mt 1:22-23; Lc 1:27,31,35; Ro 9:5; 1 Ti 2:5)',
'El Señor Jesús, en su naturaleza humana así unida a la divina en la persona del Hijo, fue santificado y ungido con el Espíritu Santo sin medida, teniendo en sí todos los tesoros de la sabiduría y del conocimiento; en él agradó al Padre que habitase toda plenitud, a fin de que, siendo santo, inocente, sin mancha y lleno de gracia y de verdad, fuera plenamente apto para ejercer el oficio de mediador y fiador; oficio que no tomó para sí, sino que fue llamado a él por su Padre, quien también puso en su mano todo poder y juicio, y le dio mandamiento de ejecutarlos. (Sal 45:7; Hch 10:38; Jn 3:34; Col 2:3; Col 1:19; He 7:26; Jn 1:14; He 5:5; Jn 5:22,27; Mt 28:18; Hch 2:36)',
'Este oficio lo asumió el Señor Jesús con toda buena voluntad, y para desempeñarlo fue hecho bajo la ley, la cumplió perfectamente, y sufrió el castigo que nos correspondía a nosotros, que debimos haberlo llevado y padecido, siendo hecho pecado y maldición por nosotros; soportando las más terribles aflicciones en su alma y los más dolorosos padecimientos en su cuerpo; fue crucificado y murió, y permaneció en el estado de los muertos, pero sin ver corrupción; al tercer día resucitó de entre los muertos con el mismo cuerpo en que padeció, con el cual también ascendió al cielo, donde está sentado a la diestra de su Padre intercediendo, y de donde volverá para juzgar a los hombres y a los ángeles al fin del mundo. (Sal 40:7-8; He 10:5-10; Gá 4:4; Mt 3:15; Gá 3:13; Is 53:6; 1 P 3:18; 2 Co 5:21; Mt 26:37-38; Lc 22:44; Mt 27:46; Hch 13:37; 1 Co 15:3-4; Jn 20:25,27; Mr 16:19; Hch 1:9-11; Ro 8:34; He 9:24; Hch 10:42; Ro 14:9-10; 2 P 2:4)',
'El Señor Jesús, por su perfecta obediencia y por el sacrificio de sí mismo que ofreció a Dios una sola vez por medio del Espíritu eterno, ha satisfecho plenamente la justicia de Dios, ha conseguido la reconciliación y ha comprado una herencia eterna en el reino de los cielos para todos aquellos que el Padre le ha dado. (He 9:14; He 10:14; Ro 3:25-26; Jn 17:2; He 9:15)',
'Aunque el precio de la redención no fue realmente pagado por Cristo sino hasta después de su encarnación, la virtud, la eficacia y los beneficios de la misma fueron comunicados a los elegidos en todas las épocas, desde el principio del mundo, en y por aquellas promesas, tipos y sacrificios en los que fue revelado y señalado como la simiente que heriría la cabeza de la serpiente, y el cordero inmolado desde la fundación del mundo, siendo el mismo ayer, y hoy, y por los siglos. (1 Co 4:10; He 4:2; 1 P 1:10-11; Ap 13:8; He 13:8)',
'Cristo, en la obra de mediación, actúa conforme a ambas naturalezas, haciendo por cada naturaleza lo que es propio de ella; aunque, por razón de la unidad de la persona, lo que es propio de una naturaleza algunas veces se atribuye en la Escritura a la persona denominada por la otra naturaleza. (Jn 3:13; Hch 20:28)',
'A todos aquellos para quienes Cristo ha obtenido redención eterna, cierta y eficazmente la aplica y comunica, haciendo intercesión por ellos, uniéndolos a sí mismo por su Espíritu, revelándoles en la Palabra y por ella el misterio de la salvación, persuadiéndoles a creer y obedecer, gobernando sus corazones por su Palabra y Espíritu, y venciendo a todos sus enemigos por su omnipotente poder y sabiduría, de tal manera y por tales medios como son más consonantes con su maravillosa e inescrutable dispensación; y todo ello por gracia libre y absoluta, sin ninguna condición prevista en ellos para granjearla. (Jn 6:37; Jn 10:15-16; Jn 17:9; Ro 5:10; Jn 17:6; Ef 1:9; 1 Jn 5:20; Ro 8:9,14; Sal 110:1; 1 Co 15:25-26; Jn 3:8; Ef 1:8)',
'Este oficio de mediador entre Dios y el hombre es propio solamente de Cristo, quien es el profeta, sacerdote y rey de la iglesia de Dios; y no puede, ni en todo ni en parte, ser transferido de él a ningún otro. (1 Ti 2:5)',
'Este número y orden de oficios es necesario: pues por nuestra ignorancia, necesitamos su oficio profético; por nuestra alienación de Dios y la imperfección aun de nuestros mejores servicios, necesitamos su oficio sacerdotal para reconciliarnos y presentarnos aceptos a Dios; y por nuestra aversión y total incapacidad para volver a Dios, y para nuestro rescate y seguridad frente a nuestros adversarios espirituales, necesitamos su oficio real para convencernos, subyugarnos, atraernos, sostenernos, librarnos y preservarnos para su reino celestial. (Jn 1:18; Col 1:21; Gá 5:17; Jn 16:8; Sal 110:3; Lc 1:74-75)'
]},
{ t: 'Del libre albedrío', p: [
'Dios ha dotado la voluntad del hombre de una libertad natural y de un poder de actuar por elección, de tal manera que ni es forzada ni determinada a hacer el bien o el mal por ninguna necesidad de su naturaleza. (Mt 17:12; Stg 1:14; Dt 30:19)',
'El hombre, en su estado de inocencia, tenía libertad y poder para querer y hacer lo que era bueno y agradable a Dios; pero era mudable, de manera que podía caer de dicho estado. (Ec 7:29; Gn 3:6)',
'El hombre, por su caída a un estado de pecado, ha perdido por completo toda capacidad de querer ningún bien espiritual que acompañe a la salvación; de modo que, como hombre natural, estando enteramente opuesto a ese bien y muerto en el pecado, no puede por sus propias fuerzas convertirse a sí mismo, ni siquiera prepararse para ello. (Ro 5:6; Ro 8:7; Ef 2:1,5; Tit 3:3-5; Jn 6:44)',
'Cuando Dios convierte a un pecador y lo traslada al estado de gracia, lo libra de su servidumbre natural bajo el pecado y, por su sola gracia, lo capacita para querer y hacer libremente lo que es espiritualmente bueno; no obstante, por razón de la corrupción que le queda, no quiere perfecta ni únicamente lo que es bueno, sino que también quiere lo que es malo. (Col 1:13; Jn 8:36; Fil 2:13; Ro 7:15,18-19,21,23)',
'Solo en el estado de gloria la voluntad del hombre es hecha perfecta e inmutablemente libre para el bien solamente. (Ef 4:13)'
]},
{ t: 'Del llamamiento eficaz', p: [
'A aquellos a quienes Dios ha predestinado para vida, le place, en su tiempo señalado y aceptado, llamarlos eficazmente por su Palabra y su Espíritu, sacándolos del estado de pecado y muerte en que están por naturaleza, a la gracia y salvación por Jesucristo; iluminando sus mentes espiritual y salvadoramente para que entiendan las cosas de Dios; quitándoles el corazón de piedra y dándoles un corazón de carne; renovando sus voluntades y, por su poder omnipotente, inclinándolos hacia el bien y atrayéndolos eficazmente a Jesucristo; pero de tal manera que vienen con absoluta libertad, habiendo sido hechos voluntarios por su gracia. (Ro 8:30; Ro 11:7; Ef 1:10-11; 2 Ts 2:13-14; Ef 2:1-6; Hch 26:18; Ef 1:17-18; Ez 36:26; Dt 30:6; Ez 36:27; Ef 1:19; Sal 110:3; Cnt 1:4)',
'Este llamamiento eficaz proviene solamente de la gracia libre y especial de Dios, no de ninguna cosa prevista en el hombre, ni de ningún poder o agencia en la criatura que coopere con su gracia especial, estando la criatura totalmente pasiva en ello, muerta en delitos y pecados, hasta que, vivificada y renovada por el Espíritu Santo, es capacitada para responder a este llamamiento y abrazar la gracia ofrecida y comunicada en él, y ello por un poder no inferior al que resucitó a Cristo de los muertos. (2 Ti 1:9; Ef 2:8; 1 Co 2:14; Ef 2:5; Jn 5:25; Ef 1:19-20)',
'Los niños elegidos que mueren en la infancia son regenerados y salvados por Cristo mediante el Espíritu, quien obra cuándo, dónde y cómo le place; lo mismo ocurre con todas las personas elegidas que son incapaces de ser llamadas exteriormente por el ministerio de la Palabra. (Jn 3:3,5-6; Jn 3:8)',
'Otros, no elegidos, aunque sean llamados por el ministerio de la Palabra y tengan algunas operaciones comunes del Espíritu, como no son atraídos eficazmente por el Padre, no quieren ni pueden venir verdaderamente a Cristo y, por tanto, no pueden ser salvos; mucho menos pueden serlo los hombres que no reciben la religión cristiana, por diligentes que sean en ajustar sus vidas conforme a la luz de la naturaleza y a la ley de la religión que profesan. (Mt 22:14; Mt 13:20-21; He 6:4-5; Jn 6:44-45,65; 1 Jn 2:24-25; Hch 4:12; Jn 4:22; Jn 17:3)'
]},
{ t: 'De la justificación', p: [
'A quienes Dios llama eficazmente, también los justifica gratuitamente; no infundiendo justicia en ellos, sino perdonándoles sus pecados, y contando y aceptando sus personas como justas; no por nada obrado en ellos o hecho por ellos, sino solamente por causa de Cristo; no imputándoles la fe misma, ni el acto de creer, ni ninguna otra obediencia evangélica como su justicia, sino imputándoles la obediencia activa de Cristo a toda la ley y su obediencia pasiva en su muerte, como su justicia total y única por la fe; la cual fe no la tienen de sí mismos: es don de Dios. (Ro 3:24; Ro 8:30; Ro 4:5-8; Ef 1:7; 1 Co 1:30-31; Ro 5:17-19; Fil 3:8-9; Ef 2:8-10; Jn 1:12; Ro 5:17)',
'La fe que así recibe a Cristo y descansa en él y en su justicia es el único instrumento de la justificación; sin embargo, no está sola en la persona justificada, sino que siempre va acompañada de todas las demás gracias salvadoras; y no es una fe muerta, sino que obra por el amor. (Ro 3:28; Gá 5:6; Stg 2:17,22,26)',
'Cristo, por su obediencia y muerte, saldó plenamente la deuda de todos los que son justificados; y por el sacrificio de sí mismo en la sangre de su cruz, sufriendo en lugar de ellos el castigo que merecían, hizo una satisfacción propia, real y plena a la justicia de Dios a favor de ellos; sin embargo, por cuanto Cristo fue dado por el Padre para ellos, y su obediencia y satisfacción aceptadas en lugar de las de ellos, y ambas gratuitamente, no por nada en ellos, su justificación es solamente de gracia gratuita, a fin de que tanto la exacta justicia como la rica gracia de Dios fuesen glorificadas en la justificación de los pecadores. (He 10:14; 1 P 1:18-19; Is 53:5-6; Ro 8:32; 2 Co 5:21; Ro 3:26; Ef 1:6-7; Ef 2:7)',
'Dios decretó desde toda la eternidad justificar a todos los elegidos, y Cristo, en la plenitud del tiempo, murió por los pecados de ellos y resucitó para su justificación; sin embargo, no son justificados personalmente hasta que el Espíritu Santo, en el tiempo debido, les aplica realmente a Cristo. (Gá 3:8; 1 P 1:2; 1 Ti 2:6; Ro 4:25; Col 1:21-22; Tit 3:4-7)',
'Dios continúa perdonando los pecados de los que son justificados; y aunque estos nunca pueden caer del estado de justificación, pueden, sin embargo, por sus pecados, caer bajo el desagrado paternal de Dios; y en esa condición, por lo general, no les es restaurada la luz de su rostro hasta que se humillan, confiesan sus pecados, piden perdón y renuevan su fe y arrepentimiento. (Mt 6:12; 1 Jn 1:7,9; Jn 10:28; Sal 89:31-33; Sal 32:5; Sal 51; Mt 26:75)',
'La justificación de los creyentes bajo el Antiguo Testamento fue, en todos estos respectos, una y la misma que la justificación de los creyentes bajo el Nuevo Testamento. (Gá 3:9; Ro 4:22-24)'
]},
{ t: 'De la adopción', p: [
'A todos aquellos que son justificados, Dios se dignó, en su único Hijo Jesucristo y por causa de él, hacerlos partícipes de la gracia de la adopción, por la cual son contados en el número de los hijos de Dios y gozan de las libertades y privilegios de tales; llevan su nombre, reciben el espíritu de adopción, tienen acceso al trono de la gracia con confianza, son capacitados para clamar «Abba, Padre», son compadecidos, protegidos, provistos y corregidos por él como por un padre, pero nunca desechados, sino sellados para el día de la redención, y heredan las promesas como herederos de la salvación eterna. (Ef 1:5; Gá 4:4-5; Jn 1:12; Ro 8:17; 2 Co 6:18; Ap 3:12; Ro 8:15; Gá 4:6; Ef 2:18; Sal 103:13; Pr 14:26; 1 P 5:7; He 12:6; Is 54:8-9; Lm 3:31; Ef 4:30; He 6:12)'
]},
{ t: 'De la santificación', p: [
'Los que están unidos a Cristo, eficazmente llamados y regenerados, teniendo un nuevo corazón y un nuevo espíritu creados en ellos por virtud de la muerte y resurrección de Cristo, son además santificados real y personalmente por la misma virtud, por su Palabra y su Espíritu que moran en ellos; el dominio del cuerpo entero del pecado es destruido, y sus diversas concupiscencias son debilitadas y mortificadas más y más, y ellos son más y más vivificados y fortalecidos en todas las gracias salvadoras, para la práctica de toda verdadera santidad, sin la cual nadie verá al Señor. (Hch 20:32; Ro 6:5-6; Jn 17:17; Ef 3:16-19; 1 Ts 5:21-23; Ro 6:14; Gá 5:24; Col 1:11; 2 Co 7:1; He 12:14)',
'Esta santificación se extiende a todo el hombre, aunque es imperfecta en esta vida: quedan aún restos de corrupción en todas sus partes, de donde surge una guerra continua e irreconciliable: la carne codicia contra el espíritu, y el espíritu contra la carne. (1 Ts 5:23; Ro 7:18,23; Gá 5:17; 1 P 2:11)',
'En esta guerra, aunque la corrupción que queda prevalezca mucho por algún tiempo, sin embargo, mediante el continuo suministro de fuerza de parte del Espíritu santificador de Cristo, la parte regenerada vence; y así los santos crecen en la gracia, perfeccionando la santidad en el temor de Dios, prosiguiendo una vida celestial, en obediencia evangélica a todos los mandatos que Cristo, como cabeza y rey, les ha prescrito en su Palabra. (Ro 7:23; Ro 6:14; Ef 4:15-16; 2 Co 3:18; 2 Co 7:1)'
]},
{ t: 'De la fe salvadora', p: [
'La gracia de la fe, por la cual los elegidos son capacitados para creer para la salvación de sus almas, es obra del Espíritu de Cristo en sus corazones, y ordinariamente se produce por el ministerio de la Palabra; por el cual, y por la administración del bautismo y la cena del Señor, la oración y otros medios señalados por Dios, esa fe aumenta y se fortalece. (2 Co 4:13; Ef 2:8; Ro 10:14,17; Lc 17:5; 1 P 2:2; Hch 20:32)',
'Por esta fe el cristiano cree que es verdadero todo lo revelado en la Palabra por la autoridad de Dios mismo, y percibe en ella una excelencia superior a todos los demás escritos y a todas las cosas del mundo, pues muestra la gloria de Dios en sus atributos, la excelencia de Cristo en su naturaleza y oficios, y el poder y la plenitud del Espíritu Santo en sus operaciones; y así es capacitado para confiar su alma a la verdad así creída; y actúa de manera diferente según sea lo que cada pasaje en particular contenga: prestando obediencia a los mandatos, temblando ante las amenazas y abrazando las promesas de Dios para esta vida y la venidera. Pero los actos principales de la fe salvadora tienen que ver de manera inmediata con Cristo: aceptarlo, recibirlo y descansar solo en él para la justificación, la santificación y la vida eterna, en virtud del pacto de gracia. (Hch 24:14; Sal 19:7-10; Sal 119:72; 2 Ti 1:12; Jn 15:14; Is 66:2; He 11:13; Jn 1:12; Hch 16:31; Gá 2:20; Hch 15:11)',
'Esta fe, aunque difiere en grados y puede ser débil o fuerte, aun en su grado mínimo es de una clase y naturaleza diferente (como lo es toda otra gracia salvadora) de la fe y gracia común de los creyentes temporales; y por tanto, aunque muchas veces sea atacada y debilitada, sale vencedora, creciendo en muchos hasta alcanzar la plena seguridad por medio de Cristo, quien es tanto el autor como el consumador de nuestra fe. (He 5:13-14; Mt 6:30; Ro 4:19-20; 2 P 1:1; Ef 6:16; 1 Jn 5:4-5; He 6:11-12; Col 2:2; He 12:2)'
]},
{ t: 'Del arrepentimiento para vida y salvación', p: [
'A aquellos de los elegidos que se convierten en edad madura, habiendo vivido algún tiempo en el estado natural y servido en él a diversas concupiscencias y placeres, Dios, en su llamamiento eficaz, les da arrepentimiento para vida. (Tit 3:2-5)',
'No hay nadie que haga el bien y no peque; y los mejores de los hombres pueden, por el poder y el engaño de la corrupción que mora en ellos, junto con la fuerza de la tentación, caer en grandes pecados y provocaciones; por lo cual Dios, en el pacto de gracia, ha provisto misericordiosamente que los creyentes que así pequen y caigan sean renovados por el arrepentimiento para salvación. (Ec 7:20; Lc 22:31-32)',
'Este arrepentimiento salvador es una gracia evangélica por la cual una persona, a quien el Espíritu Santo hace consciente de las múltiples maldades de su pecado, por la fe en Cristo se humilla por él con tristeza según Dios, aborrecimiento de él y aun abominación de sí misma, orando por el perdón y por fuerza de gracia, con el propósito y el empeño, mediante la provisión del Espíritu, de andar delante de Dios de modo que le agrade en todo. (Zac 12:10; Hch 11:18; Ez 36:31; 2 Co 7:11; Sal 119:6,128)',
'Como el arrepentimiento ha de continuar a lo largo de toda nuestra vida, por razón del cuerpo de muerte y de sus impulsos, es deber de cada hombre arrepentirse de sus pecados particulares conocidos, de manera particular. (Lc 19:8; 1 Ti 1:13,15)',
'Tal es la provisión que Dios ha hecho por medio de Cristo en el pacto de gracia para la preservación de los creyentes para salvación, que aunque no hay pecado tan pequeño que no merezca la condenación, no hay pecado tan grande que traiga condenación sobre los que se arrepienten; lo cual hace necesaria la predicación constante del arrepentimiento. (Ro 6:23; Is 1:16-18; Is 55:7)'
]},
{ t: 'De las buenas obras', p: null },
{ t: 'De la perseverancia de los santos', p: null },
{ t: 'De la seguridad de la gracia y de la salvación', p: null },
{ t: 'De la ley de Dios', p: null },
{ t: 'Del evangelio y del alcance de su gracia', p: null },
{ t: 'De la libertad cristiana y de la libertad de conciencia', p: null },
{ t: 'De la adoración religiosa y del día de reposo', p: null },
{ t: 'De los juramentos y votos lícitos', p: null },
{ t: 'Del magistrado civil', p: null },
{ t: 'Del matrimonio', p: null },
{ t: 'De la iglesia', p: null },
{ t: 'De la comunión de los santos', p: null },
{ t: 'Del bautismo y la cena del Señor', p: null },
{ t: 'Del bautismo', p: null },
{ t: 'De la cena del Señor', p: null },
{ t: 'Del estado del hombre después de la muerte y de la resurrección de los muertos', p: null },
{ t: 'Del juicio final', p: null }
]},
west: {
titulo: 'Confesión de Fe de Westminster (1647)',
nota: 'Confesión de Fe de Westminster de 1647. Texto histórico de dominio público. Las referencias bíblicas entre paréntesis son las pruebas señaladas por la Asamblea.',
caps: [
{ t: 'De las Santas Escrituras', p: null },
{ t: 'De Dios y de la Santísima Trinidad', p: null },
{ t: 'Del decreto eterno de Dios', p: null },
{ t: 'De la creación', p: null },
{ t: 'De la providencia', p: null },
{ t: 'De la caída del hombre, del pecado y su castigo', p: null },
{ t: 'Del pacto de Dios con el hombre', p: null },
{ t: 'De Cristo el Mediador', p: null },
{ t: 'Del libre albedrío', p: null },
{ t: 'Del llamamiento eficaz', p: null },
{ t: 'De la justificación', p: null },
{ t: 'De la adopción', p: null },
{ t: 'De la santificación', p: null },
{ t: 'De la fe salvadora', p: null },
{ t: 'Del arrepentimiento para vida', p: null },
{ t: 'De las buenas obras', p: null },
{ t: 'De la perseverancia de los santos', p: null },
{ t: 'De la seguridad de la gracia y de la salvación', p: null },
{ t: 'De la ley de Dios', p: null },
{ t: 'De la libertad cristiana y de la libertad de conciencia', p: null },
{ t: 'De la adoración religiosa y del día de reposo', p: null },
{ t: 'De los juramentos y votos lícitos', p: null },
{ t: 'Del magistrado civil', p: null },
{ t: 'Del matrimonio y del divorcio', p: null },
{ t: 'De la iglesia', p: null },
{ t: 'De la comunión de los santos', p: null },
{ t: 'De los sacramentos', p: null },
{ t: 'Del bautismo', p: null },
{ t: 'De la cena del Señor', p: null },
{ t: 'De las censuras eclesiásticas', p: null },
{ t: 'De los sínodos y concilios', p: null },
{ t: 'Del estado del hombre después de la muerte y de la resurrección de los muertos', p: null },
{ t: 'Del juicio final', p: null }
]}
};
