/* Confesiones de fe — textos históricos de dominio público, versión en español */
const CONFESIONES = {
lbc: {
titulo: 'Confesión de Fe Bautista de Londres (1689)',
nota: 'Confesión de Fe Bautista de Londres de 1689. Texto histórico de dominio público. Las referencias bíblicas entre paréntesis son las pruebas señaladas por los autores.',
caps: [
{ t: 'De las Santas Escrituras', p: [
'La Santa Escritura es la única regla suficiente, segura e infalible de todo conocimiento salvador, fe y obediencia. Aunque la luz de la naturaleza y las obras de la creación y de la providencia manifiestan de tal manera la bondad, sabiduría y poder de Dios que dejan a los hombres sin excusa, no son suficientes para dar aquel conocimiento de Dios y de su voluntad que es necesario para la salvación. Por tanto, agradó al Señor, en distintas épocas y de diversas maneras, revelarse a sí mismo y declarar su voluntad a su iglesia; y después, para preservar y propagar mejor la verdad, y para el más seguro establecimiento y consuelo de la iglesia contra la corrupción de la carne y la malicia de Satanás y del mundo, le agradó poner por escrito esa revelación en su totalidad, lo cual hace a las Santas Escrituras absolutamente necesarias, habiendo cesado ya aquellas maneras anteriores por las cuales Dios revelaba su voluntad a su pueblo. (2 Ti 3:15-17; Is 8:20; Lc 16:29,31; Ef 2:20; Ro 1:19-21; Ro 2:14-15; Sal 19:1-3; He 1:1; Pr 22:19-21; Ro 15:4; 2 P 1:19-20)',
'Bajo el nombre de Santa Escritura, o Palabra de Dios escrita, se contienen ahora todos los libros del Antiguo y Nuevo Testamento, que son: Génesis, Éxodo, Levítico, Números, Deuteronomio, Josué, Jueces, Rut, 1 Samuel, 2 Samuel, 1 Reyes, 2 Reyes, 1 Crónicas, 2 Crónicas, Esdras, Nehemías, Ester, Job, Salmos, Proverbios, Eclesiastés, Cantar de los Cantares, Isaías, Jeremías, Lamentaciones, Ezequiel, Daniel, Oseas, Joel, Amós, Abdías, Jonás, Miqueas, Nahúm, Habacuc, Sofonías, Hageo, Zacarías, Malaquías, Mateo, Marcos, Lucas, Juan, Hechos, Romanos, 1 Corintios, 2 Corintios, Gálatas, Efesios, Filipenses, Colosenses, 1 Tesalonicenses, 2 Tesalonicenses, 1 Timoteo, 2 Timoteo, Tito, Filemón, Hebreos, Santiago, 1 Pedro, 2 Pedro, 1 Juan, 2 Juan, 3 Juan, Judas y Apocalipsis. Todos ellos son dados por inspiración de Dios para ser la regla de fe y de vida. (2 Ti 3:16)',
'Los libros comúnmente llamados Apócrifos, no siendo de inspiración divina, no forman parte del canon o regla de la Escritura y, por tanto, no tienen autoridad para la iglesia de Dios, ni deben ser aprobados o usados de otra manera que otros escritos humanos. (Lc 24:27,44; Ro 3:2)',
'La autoridad de la Santa Escritura, por la cual debe ser creída, no depende del testimonio de ningún hombre o iglesia, sino enteramente de Dios (quien es la verdad misma), su autor; por lo tanto, debe ser recibida porque es la Palabra de Dios. (2 P 1:19-21; 2 Ti 3:16; 1 Ts 2:13; 1 Jn 5:9)',
'Podemos ser movidos e inducidos por el testimonio de la iglesia de Dios a una estima alta y reverente de las Santas Escrituras; y el carácter celestial de su contenido, la eficacia de su doctrina, la majestad de su estilo, la armonía de todas sus partes, el fin que persigue en su totalidad (que es dar toda la gloria a Dios), la plena revelación que hace del único camino de salvación del hombre, y muchas otras excelencias incomparables y plena perfección de la misma, son argumentos por los cuales da abundante evidencia de ser la Palabra de Dios. Sin embargo, nuestra plena persuasión y certeza de su verdad infalible y autoridad divina proviene de la obra interna del Espíritu Santo, que da testimonio por medio de la Palabra y con la Palabra en nuestros corazones. (Jn 16:13-14; 1 Co 2:10-12; 1 Jn 2:20,27)',
'Todo el consejo de Dios tocante a todas las cosas necesarias para su propia gloria, la salvación del hombre, la fe y la vida, está expresamente declarado o necesariamente contenido en la Santa Escritura; a la cual nada, en ningún tiempo, ha de añadirse, ni por nueva revelación del Espíritu ni por las tradiciones de los hombres. Sin embargo, reconocemos que la iluminación interna del Espíritu de Dios es necesaria para el entendimiento salvador de las cosas reveladas en la Palabra, y que hay algunas circunstancias tocantes a la adoración de Dios y al gobierno de la iglesia, comunes a las acciones y sociedades humanas, que han de ordenarse conforme a la luz de la naturaleza y de la prudencia cristiana, según las reglas generales de la Palabra, que siempre deben observarse. (2 Ti 3:15-17; Gá 1:8-9; Jn 6:45; 1 Co 2:9-12; 1 Co 11:13-14; 1 Co 14:26,40)',
'No todas las cosas contenidas en la Escritura son igualmente claras en sí mismas, ni igualmente claras para todos; sin embargo, las cosas que necesariamente deben saberse, creerse y observarse para la salvación se proponen y explican tan claramente en uno u otro lugar de la Escritura, que no solo los eruditos, sino también los que no lo son, pueden alcanzar un entendimiento suficiente de ellas mediante el debido uso de los medios ordinarios. (2 P 3:16; Sal 19:7; Sal 119:130)',
'El Antiguo Testamento en hebreo (que era la lengua nativa del pueblo de Dios en la antigüedad) y el Nuevo Testamento en griego (que en el tiempo en que fue escrito era la lengua más generalmente conocida entre las naciones), siendo inspirados inmediatamente por Dios y mantenidos puros a lo largo de los siglos por su cuidado y providencia singulares, son por tanto auténticos; de modo que en toda controversia religiosa la iglesia debe apelar a ellos como autoridad final. Pero como estas lenguas originales no son conocidas por todo el pueblo de Dios, que tiene derecho a las Escrituras e interés en ellas, y a quien se le manda leerlas y escudriñarlas en el temor de Dios, deben traducirse a la lengua común de toda nación a la que lleguen, para que, morando abundantemente la Palabra de Dios en todos, puedan adorarle de manera aceptable y, por la paciencia y consolación de las Escrituras, tengan esperanza. (Ro 3:2; Is 8:20; Hch 15:15; Jn 5:39; 1 Co 14:6,9,11-12,24,28; Col 3:16)',
'La regla infalible de interpretación de la Escritura es la Escritura misma; y, por consiguiente, cuando surge una duda respecto al sentido verdadero y pleno de cualquier pasaje (que no es múltiple, sino uno), este debe buscarse mediante otros pasajes que hablen con más claridad. (2 P 1:20-21; Hch 15:15-16)',
'El juez supremo, por el cual deben decidirse todas las controversias religiosas y examinarse todos los decretos de concilios, las opiniones de los escritores antiguos, las doctrinas de hombres y los espíritus privados, y en cuya sentencia hemos de descansar, no puede ser otro que la Santa Escritura entregada por el Espíritu. A dicha Escritura así entregada se reduce nuestra fe en última instancia. (Mt 22:29,31-32; Ef 2:20; Hch 28:23)'
]},
{ t: 'De Dios y de la Santa Trinidad', p: [
'El Señor nuestro Dios es un solo Dios vivo y verdadero; cuya subsistencia está en sí mismo y es de sí mismo, infinito en ser y perfección; cuya esencia no puede ser comprendida por nadie sino por él mismo; espíritu purísimo, invisible, sin cuerpo, miembros ni pasiones; el único que tiene inmortalidad, que habita en luz inaccesible; inmutable, inmenso, eterno, incomprensible, todopoderoso, infinito en todo sentido, santísimo, sapientísimo, libérrimo, absolutísimo; que hace todas las cosas según el consejo de su propia voluntad inmutable y justísima, para su propia gloria; amantísimo, benigno, misericordioso, longánimo, abundante en bondad y verdad, que perdona la iniquidad, la transgresión y el pecado; galardonador de los que le buscan con diligencia; y, con todo, justísimo y terrible en sus juicios, que odia todo pecado y de ninguna manera dará por inocente al culpable. (1 Co 8:4,6; Dt 6:4; Jer 10:10; Is 48:12; Éx 3:14; Jn 4:24; 1 Ti 1:17; Dt 4:15-16; Mal 3:6; 1 R 8:27; Jer 23:23; Sal 90:2; Gn 17:1; Is 6:3; Sal 115:3; Is 46:10; Pr 16:4; Ro 11:36; Éx 34:6-7; He 11:6; Neh 9:32-33; Sal 5:5-6; Éx 34:7; Nah 1:2-3)',
'Dios, teniendo toda vida, gloria, bondad y bienaventuranza en sí mismo y de sí mismo, es el único autosuficiente, y no necesita de ninguna criatura que él haya hecho, ni deriva gloria alguna de ellas, sino que solamente manifiesta su propia gloria en ellas, por ellas, hacia ellas y sobre ellas. Él es la sola fuente de todo ser, de quien, por quien y para quien son todas las cosas; y tiene sobre todas las criaturas dominio soberanísimo para hacer por medio de ellas, para ellas o sobre ellas todo lo que le plazca. Ante su vista todas las cosas están abiertas y manifiestas; su conocimiento es infinito, infalible e independiente de la criatura, de modo que para él nada es contingente o incierto. Es santísimo en todos sus consejos, en todas sus obras y en todos sus mandatos. A él se le debe, de parte de los ángeles y de los hombres, todo culto, servicio u obediencia que como criaturas deben al Creador, y todo lo demás que él tenga a bien requerir de ellos. (Jn 5:26; Sal 148:13; Sal 119:68; Job 22:2-3; Ro 11:34-36; Dn 4:25,34-35; He 4:13; Ez 11:5; Hch 15:18; Sal 145:17; Ap 5:12-14)',
'En este Ser divino e infinito hay tres subsistencias: el Padre, el Verbo o Hijo, y el Espíritu Santo; de una misma sustancia, poder y eternidad, teniendo cada uno toda la esencia divina, sin que esta sea dividida: el Padre no es de nadie, ni por generación ni por procesión; el Hijo es eternamente engendrado del Padre; el Espíritu Santo procede del Padre y del Hijo. Todos ellos son infinitos, sin principio, y por tanto un solo Dios, que no debe ser dividido en naturaleza y ser, sino distinguido por varias propiedades relativas peculiares y relaciones personales. Esta doctrina de la Trinidad es el fundamento de toda nuestra comunión con Dios y de nuestra consoladora dependencia de él. (1 Jn 5:7; Mt 28:19; 2 Co 13:14; Éx 3:14; Jn 14:11; 1 Co 8:6; Jn 1:14,18; Jn 15:26; Gá 4:6)'
]},
{ t: 'Del decreto de Dios', p: [
'Dios ha decretado en sí mismo, desde toda la eternidad, por el sapientísimo y santísimo consejo de su propia voluntad, libre e inmutablemente, todas las cosas que suceden; sin embargo, de tal manera que Dios ni es autor del pecado ni tiene comunión con nadie en él; ni se hace violencia a la voluntad de la criatura, ni es quitada la libertad o contingencia de las causas segundas, sino más bien establecida; en lo cual se manifiesta su sabiduría en disponer todas las cosas, y su poder y fidelidad en cumplir su decreto. (Is 46:10; Ef 1:11; He 6:17; Ro 9:15,18; Stg 1:13; 1 Jn 1:5; Hch 4:27-28; Jn 19:11; Nm 23:19; Ef 1:3-5)',
'Aunque Dios conoce todo lo que puede o podría suceder bajo todas las condiciones supuestas, nada ha decretado porque lo previera como futuro o como cosa que sucedería en tales condiciones. (Hch 15:18; Ro 9:11,13,16,18)',
'Por el decreto de Dios, para la manifestación de su gloria, algunos hombres y ángeles son predestinados, o preordinados, a vida eterna por medio de Jesucristo, para alabanza de su gloriosa gracia; otros son dejados para que actúen en su pecado para su justa condenación, para alabanza de su gloriosa justicia. (1 Ti 5:21; Mt 25:34; Ef 1:5-6; Ro 9:22-23; Jud 4)',
'Estos ángeles y hombres así predestinados y preordinados están particular e inmutablemente designados, y su número es tan cierto y definido que no puede ser aumentado ni disminuido. (2 Ti 2:19; Jn 13:18)',
'A aquellos de la humanidad que están predestinados a la vida, Dios, antes de la fundación del mundo, conforme a su propósito eterno e inmutable y al consejo secreto y beneplácito de su voluntad, los ha escogido en Cristo para gloria eterna, por su mera gracia y amor, sin ninguna otra cosa en la criatura como condición o causa que le moviera a ello. (Ef 1:4,9,11; Ro 8:30; 2 Ti 1:9; 1 Ts 5:9; Ro 9:13,16; Ef 2:5,12)',
'Como Dios ha designado a los elegidos para la gloria, así también, por el propósito eterno y libérrimo de su voluntad, ha preordinado todos los medios para ello; por lo cual los que son elegidos, habiendo caído en Adán, son redimidos por Cristo, son eficazmente llamados a la fe en Cristo por su Espíritu que obra en el tiempo debido, son justificados, adoptados, santificados y guardados por su poder mediante la fe para salvación. Ningún otro es redimido por Cristo, ni eficazmente llamado, justificado, adoptado, santificado y salvado, sino solamente los elegidos. (1 P 1:2; 2 Ts 2:13; 1 Ts 5:9-10; Ro 8:30; 2 Ts 2:13; 1 P 1:5; Jn 10:26; Jn 17:9; Jn 6:64)',
'La doctrina de este alto misterio de la predestinación debe tratarse con especial prudencia y cuidado, para que los hombres, atendiendo a la voluntad de Dios revelada en su Palabra y obedeciéndola, puedan, por la certeza de su llamamiento eficaz, estar seguros de su elección eterna; de manera que esta doctrina proporcione motivo de alabanza, reverencia y admiración de Dios, y de humildad, diligencia y abundante consuelo a todos los que sinceramente obedecen el evangelio. (1 Ts 1:4-5; 2 P 1:10; Ef 1:6; Ro 11:33; Ro 11:5-6,20; Lc 10:20)'
]},
{ t: 'De la creación', p: [
'En el principio agradó a Dios Padre, Hijo y Espíritu Santo, para la manifestación de la gloria de su poder, sabiduría y bondad eternos, crear o hacer el mundo y todas las cosas que en él hay, tanto visibles como invisibles, en el espacio de seis días, y todo muy bueno. (Jn 1:2-3; He 1:2; Job 26:13; Ro 1:20; Col 1:16; Gn 1:31)',
'Después que Dios hubo hecho todas las demás criaturas, creó al hombre, varón y hembra, con almas racionales e inmortales, haciéndolos aptos para aquella vida para con Dios para la cual fueron creados; siendo hechos a imagen de Dios, en conocimiento, justicia y santidad verdadera, teniendo la ley de Dios escrita en sus corazones y el poder para cumplirla; y, sin embargo, con la posibilidad de transgredirla, al ser dejados a la libertad de su propia voluntad, que era mutable. (Gn 1:27; Gn 2:7; Ec 7:29; Gn 1:26; Ro 2:14-15; Gn 3:6)',
'Además de la ley escrita en sus corazones, recibieron el mandato de no comer del árbol del conocimiento del bien y del mal; y mientras lo guardaron, fueron felices en su comunión con Dios y tuvieron dominio sobre las criaturas. (Gn 2:17; Gn 1:26,28)'
]},
{ t: 'De la divina providencia', p: [
'Dios, el buen Creador de todas las cosas, en su infinito poder y sabiduría sostiene, dirige, dispone y gobierna a todas las criaturas y cosas, desde la más grande hasta la más pequeña, por su sapientísima y santísima providencia, para el fin para el cual fueron creadas, según su presciencia infalible y el libre e inmutable consejo de su propia voluntad; para alabanza de la gloria de su sabiduría, poder, justicia, infinita bondad y misericordia. (He 1:3; Job 38:11; Is 46:10-11; Sal 135:6; Mt 10:29-31; Ef 1:11)',
'Aunque en relación con la presciencia y el decreto de Dios, la causa primera, todas las cosas suceden inmutable e infaliblemente, de modo que nada acontece a nadie por azar o fuera de su providencia; sin embargo, por la misma providencia, Dios las ordena de tal manera que ocurran conforme a la naturaleza de las causas segundas, sea necesaria, libre o contingentemente. (Hch 2:23; Pr 16:33; Gn 8:22)',
'Dios, en su providencia ordinaria, hace uso de medios; sin embargo, es libre para obrar sin ellos, sobre ellos y contra ellos, según le plazca. (Hch 27:31,44; Is 55:10-11; Os 1:7; Ro 4:19-21; Dn 3:27)',
'El poder omnipotente, la sabiduría inescrutable y la bondad infinita de Dios se manifiestan en su providencia de tal manera que su consejo determinado se extiende aun hasta la primera caída y a todas las demás acciones pecaminosas, tanto de ángeles como de hombres (y esto no por un mero permiso), las cuales sapientísima y poderosamente limita, y asimismo ordena y gobierna de múltiples maneras para sus santísimos fines; pero de tal modo que la pecaminosidad de dichas acciones procede solamente de las criaturas y no de Dios, quien, siendo santísimo y justísimo, ni es ni puede ser autor o aprobador del pecado. (Ro 11:32-34; 2 S 24:1 con 1 Cr 21:1; 2 R 19:28; Sal 76:10; Gn 50:20; Is 10:6-7,12; Sal 50:21; 1 Jn 2:16)',
'El sapientísimo, justísimo y clementísimo Dios muchas veces deja por algún tiempo a sus propios hijos en múltiples tentaciones y en la corrupción de sus propios corazones, para castigarlos por sus pecados anteriores o para descubrirles la fuerza oculta de la corrupción y el engaño de sus corazones, a fin de que sean humillados; y para llevarlos a una dependencia de él más íntima y constante para su sostén, y para hacerlos más vigilantes contra todas las ocasiones futuras de pecado, y para otros muchos fines santos y justos. De modo que todo lo que acontece a cualquiera de sus elegidos es por su designio, para su gloria y el bien de ellos. (2 Cr 32:25-26,31; 2 Co 12:7-9; Ro 8:28)',
'En cuanto a aquellos hombres malvados e impíos a quienes Dios, como juez justo, ciega y endurece a causa de sus pecados anteriores, no solo les niega su gracia, por la cual podrían haber sido iluminados en su entendimiento y movidos en sus corazones, sino que también a veces retira los dones que tenían, y los deja expuestos a aquellas cosas que su corrupción convierte en ocasión de pecado; y además los entrega a sus propias concupiscencias, a las tentaciones del mundo y al poder de Satanás, por lo cual sucede que se endurecen a sí mismos bajo los mismos medios que Dios emplea para ablandar a otros. (Ro 1:24-26,28; Ro 11:7-8; Dt 29:4; Mt 13:12; Dt 2:30; 2 R 8:12-13; Sal 81:11-12; 2 Ts 2:10-12; Éx 8:15,32; Is 6:9-10; 1 P 2:7-8)',
'Como la providencia de Dios alcanza en general a todas las criaturas, así de una manera muy especial cuida de su iglesia y dispone todas las cosas para el bien de ella. (1 Ti 4:10; Am 9:8-9; Is 43:3-5)'
]},
{ t: 'De la caída del hombre, del pecado y su castigo', p: null },
{ t: 'Del pacto de Dios', p: null },
{ t: 'De Cristo el Mediador', p: null },
{ t: 'Del libre albedrío', p: null },
{ t: 'Del llamamiento eficaz', p: null },
{ t: 'De la justificación', p: null },
{ t: 'De la adopción', p: null },
{ t: 'De la santificación', p: null },
{ t: 'De la fe salvadora', p: null },
{ t: 'Del arrepentimiento para vida y salvación', p: null },
{ t: 'De las buenas obras', p: null },
{ t: 'De la perseverancia de los santos', p: null },
{ t: 'De la seguridad de la gracia y de la salvación', p: null },
{ t: 'De la ley de Dios', p: null },
{ t: 'Del evangelio y del alcance de su gracia', p: null },
{ t: 'De la libertad cristiana y de la libertad de conciencia', p: null },
{ t: 'De la adoración religiosa y del día de reposo', p: null },
{ t: 'De los juramentos y votos lícitos', p: null },
{ t: 'Del magistrado civil', p: null },
{ t: 'Del matrimonio', p: null },
{ t: 'De la iglesia', p: null },
{ t: 'De la comunión de los santos', p: null },
{ t: 'Del bautismo y la cena del Señor', p: null },
{ t: 'Del bautismo', p: null },
{ t: 'De la cena del Señor', p: null },
{ t: 'Del estado del hombre después de la muerte y de la resurrección de los muertos', p: null },
{ t: 'Del juicio final', p: null }
]},
west: {
titulo: 'Confesión de Fe de Westminster (1647)',
nota: 'Confesión de Fe de Westminster de 1647. Texto histórico de dominio público. Las referencias bíblicas entre paréntesis son las pruebas señaladas por la Asamblea.',
caps: [
{ t: 'De las Santas Escrituras', p: null },
{ t: 'De Dios y de la Santísima Trinidad', p: null },
{ t: 'Del decreto eterno de Dios', p: null },
{ t: 'De la creación', p: null },
{ t: 'De la providencia', p: null },
{ t: 'De la caída del hombre, del pecado y su castigo', p: null },
{ t: 'Del pacto de Dios con el hombre', p: null },
{ t: 'De Cristo el Mediador', p: null },
{ t: 'Del libre albedrío', p: null },
{ t: 'Del llamamiento eficaz', p: null },
{ t: 'De la justificación', p: null },
{ t: 'De la adopción', p: null },
{ t: 'De la santificación', p: null },
{ t: 'De la fe salvadora', p: null },
{ t: 'Del arrepentimiento para vida', p: null },
{ t: 'De las buenas obras', p: null },
{ t: 'De la perseverancia de los santos', p: null },
{ t: 'De la seguridad de la gracia y de la salvación', p: null },
{ t: 'De la ley de Dios', p: null },
{ t: 'De la libertad cristiana y de la libertad de conciencia', p: null },
{ t: 'De la adoración religiosa y del día de reposo', p: null },
{ t: 'De los juramentos y votos lícitos', p: null },
{ t: 'Del magistrado civil', p: null },
{ t: 'Del matrimonio y del divorcio', p: null },
{ t: 'De la iglesia', p: null },
{ t: 'De la comunión de los santos', p: null },
{ t: 'De los sacramentos', p: null },
{ t: 'Del bautismo', p: null },
{ t: 'De la cena del Señor', p: null },
{ t: 'De las censuras eclesiásticas', p: null },
{ t: 'De los sínodos y concilios', p: null },
{ t: 'Del estado del hombre después de la muerte y de la resurrección de los muertos', p: null },
{ t: 'Del juicio final', p: null }
]}
};
